### ISSUE TITLE
recommend 'random route' no pokestop visit

### ISSUE THREAD

**Issue by fuckNIANTIC** [Nader-Sl/Hackemon#100]
not sure if its possible, but just wondering if a 'no trigger pokestop' is possible. Sometimes i just want to catch the stardust from pokemon catches but not get the exp from visiting pokestop or items? would this be possible? or maybe ability to change the frequency of visiting pokestop.

**Comment by Driesboy** [comment]
i think soon

**Comment by ciannaaperta** [comment]
Often the bot stucks at the first pokestop visited. Continues spinning the same pokestop obviously gaining no exp and items. IT'S NOT A BAN it just keeps spinning the same pokemon. Please insert a button to skip pokestop or anything like that.
