### ISSUE TITLE
Instant Catchflee

### ISSUE THREAD

**Issue by manuelex20** [Nader-Sl/Hackemon#101]
I just open the bot, logged in and soft ban :/

**Comment by Aid-en** [comment]
same!

**Comment by Driesboy** [comment]
do you have change the coordinates?

**Comment by twk4924** [comment]
soft ban is small case bro....
i got perm ban on my second account at this morning and i stop bot around 20 hour ago
i only bot 8xx pokemon & 8xx poke stop a day... lucky it was my second account
i tot my setting are safe enuf ....but still got ban ><
