### ISSUE TITLE
Phone configuration

### ISSUE THREAD

**Issue by Epic81** [Nader-Sl/Hackemon#102]
When i first ran the bot I configured my phone settings to android and filled in the sections.
However every time I close the bot its shows iphone settings.
Do I need to change the values everytime?
![screen shot 08-18-16 at 02 08 am](https://cloud.githubusercontent.com/assets/20747949/17768416/c0dfd2d4-64e8-11e6-8f69-e1d606cb1d5e.PNG)

**Comment by Driesboy** [comment]
wtf!

**Comment by Driesboy** [comment]
you dont need to change!
its the hacking os!
