### ISSUE TITLE
Google Error com.google.protobuf

### ISSUE THREAD

**Issue by jony215** [Nader-Sl/Hackemon#103]
Hello,
since the last update I got this error attached to this post.

>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> salt.kP: Unknown exception occurred.
>         at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.new.K0M0qVvnMS(Unknown Source)
>         at com.hackemon.Hackemon.main(Unknown Source)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
> com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:465)
>         at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>         ... 3 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
> rotocolBufferException: Contents of buffer are null
>         at salt.kW.get(Unknown Source)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:74)
>         at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
> e.call(OnSubscribeToObservableFuture.java:43)
>         at rx.Observable.unsafeSubscribe(Observable.java:9861)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
>         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>         at rx.Observable.subscribe(Observable.java:9957)
>         at rx.Observable.subscribe(Observable.java:9924)
>         at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
> ava:445)
>         ... 4 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
> r are null
>         at salt.kY.QeSuAnCe00(Unknown Source)
>         at salt.kV.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> Batchvorgang abbrechen (J/N)?

[errorlog.pdf](https://github.com/Nader-Sl/Hackemon/files/424396/errorlog.pdf)

Using a Server with Windows Server 2012 R2 - newest Java-Version. Account ist PTC.

**Comment by wqna** [comment]
i got the same pb..

**Comment by yoyos** [comment]
Just got same error on one of my account.
Does this mean permaban ?

**Comment by jony215** [comment]
No, this is no ban. I mean this is a problem by the software. Problem is still here at version 1.6
