### ISSUE TITLE
pokemon? hardly any?

### ISSUE THREAD

**Issue by fuckNIANTIC** [Nader-Sl/Hackemon#107]
is it just me, or does Pokemons almost seem like its non-existance. alot of pokestop not many pokemons caught?

**Comment by MikJohnson** [comment]
Same

**Comment by Roadieee** [comment]
the other bots seek them out and go to them. this one walks from pokestop to pokestop and only grabs the pokemon along the way (as you would in real life)

**Comment by thorclaw** [comment]
That's why you wont get banned so let's just keep it this way.

**Comment by fuckNIANTIC** [comment]
but i need my stardust V_V' also does anyone know whether generating a new device info every time you spoof to a location(another country), avoids the soft ban? has anyone tried, just out of curiosity.

**Comment by Roadieee** [comment]
nope. they strictly look at location. If you just too fast, you get soft banned. If you want pokemon from other areas, just poke snipe them.

**Comment by KutPT** [comment]
Snipping and teleportin is basically the same, i wouldnt recommend it if you want to keep it safe.

**Comment by Roadieee** [comment]
Not hardly. Your location does not change when sniping. I've never been soft-banned for sniping, however, I have been soft-banned every single time I've teleported.

**Comment by outtasync** [comment]
I wouldnt risk sniping.   The accounts I have botted on and sniped all got banned.  Even if I was very careful with the botting.  (Slow, localized areas, long delays between bot and pulling up on a device, etc)
