### ISSUE TITLE
Stops at 1 pokestop

### ISSUE THREAD

**Issue by Pokedox** [Nader-Sl/Hackemon#109]
Hello there. I am using Hackemon on Mac. And it works fine. But after visiting one pokestop. It keeps repeating to collect that one pokestop. And the bot won't select a new pokestop. 

Do I have the wrong settings? 

I am not soft / hard banned I checked. If I restart the bot it walks to the same pokestop, capturing etc. But when it reached the pokestop same problem..

**Comment by ciannaaperta** [comment]
Same thing to me. Bot is stuck on the first nearest pokestop. I haven't got any kind of ban. If I open up the game normally pokestops spin and give items. It's the bot failing at moving to new pokestops. The first one is like a black hole catching the bot forever. I'm quite sure it's a MAC only issue. Please give us a more mac-stable hackemon.

**Comment by ciannaaperta** [comment]
A very simple workaround to fix it would be to force the bot changing pokestop by excluding last coordinates from available choices.

**Comment by Pokedox** [comment]
That's even more work that GPS Spoofing.. Keep put new coordinates in until it works, not gonna work for me haha. 

Just fix it for mac sir pls!
