### ISSUE TITLE
Bot only goes to Pokestops. And doesn't catch any pokémons. 

### ISSUE THREAD

**Issue by MikJohnson** [Nader-Sl/Hackemon#110]
> [09:38:04] [Pokestop Farm] Walking to the next pokestop at {cords} using realistic ROAD_WALK routes

> [09:38:04] [Pokestop Farm] Gained 50 XP.

He is doing this the hole time. after a couple of time's he just relogs and goes ahead with ONLY going to Pokestops. The bot worked fine until nothing happened for a while. And now only goes to Pokestops.

**Comment by outtasync** [comment]
I have issues where it sees the pokemon, but never catches it.  It looks like it isnt even attempting to 
00:36:37] [Pokemon Farm] Attempt [1] to catch a RATTATA of CP = 22 | IV% = 58.0
[00:36:44] Encountered a local Pokemon..
[00:36:44] [Pokemon Farm] Attempt [1] to catch a RATTATA of CP = 22 | IV% = 58.0
[00:36:44] [Pokemon Farm] Introducing a pokeball catch error [chance 26%]
[00:36:51] Encountered a local Pokemon..
[00:36:51] [Pokemon Farm] Attempt [1] to catch a RATTATA of CP = 22 | IV% = 58.0

**Comment by MikJohnson** [comment]
Problem solved, wait a few hours, and change `ROAD_WALK` to `ROAD_FLY`.

**Comment by outtasync** [comment]
I think my problem was I had the Encounter and Ball throw delays set to 3 to 5 milliseconds, I meant them to be 3 to 5 seconds.   So upping them to 3000 and 5000 seemed to fix it.
