### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ShiroShini** [Nader-Sl/Hackemon#113]
So there are alot of good suggestions, like the walk speed randomizer and perfect catch randomizer. but those aside, I think it would be nice to have eggs implemented. As far as I know, you can't do anything with eggs. Another suggestion would be the ability to rename your pokemon from the program. or have an auto rename where I can rename my pokemon based off their IVs. Like how necrobot fork does it. That way when I open the app on my phone, I know which pokemon has which IV. Those are my only two big ones. 
Thanks for hearing me out!

**Comment by soeshark** [comment]
Rename all pokemons with iv will be one obvios flag for ban.

**Comment by ggebler** [comment]
Another great implement would be to use the lucky egg if you have X evolves pendings and choose to evolve if you have enought candies and wich cp or iv% min to do the evolve.. like Catchem does.
