### ISSUE TITLE
Trainer Info and Pokemon NOT SHOWING

### ISSUE THREAD

**Issue by CrystalEcho** [Nader-Sl/Hackemon#115]
Guy need some help here. It's a bit hard to bot without the pokemon and pokestop counts. 

Based from the discussions here its working for the others but not for everyone, both were working fine before the update. 

I'm not sure if its because of the OS, windows version or java settings.

I tried reinstaling java and getting fresh download on the bot, i tried using ptc and google account, 

Anyone have an idea on how to make it work? A change on the settings maybe.

NOT WORKING
Windows 10 x64
Java 8u102

**Comment by KutPT** [comment]
i have the same problem. windows 7 x64, latest java version too.. This started to happen after the last bot update.

**Comment by aboxx** [comment]
Have you logged into the account with your phone and gone through the introduction and chose name?

**Comment by ggebler** [comment]
Close the application, open it again, go Settings->Humanizer->Device Info->Generate.
Then Start. Hope this help you.

**Comment by twk4924** [comment]
Settings->Humanizer->Device Info->Generate.
Then Start.

not working for me =(

**Comment by GObang84** [comment]
I did a clean install and open bot , Settings->Humanizer->Device Info->Generate.
Then Start, works for me. Thanks!

**Comment by ggebler** [comment]
twk4924, reinstall (unzip the original download again). Then do these steps again. Try to generate once or twice. Hope this work out for you.

**Comment by ciannaaperta** [comment]
On mac no pokemon shown at all. Not even transferring

**Comment by twk4924** [comment]
it not work for me =(
i now trying reinstall java
after that i will update on here

**Comment by ciannaaperta** [comment]
Migrate to ninja bot

**Comment by Nader-Sl** [comment]
Fixed issue, will be included with other fixes/updates today :)
