### ISSUE TITLE
Pokéstops give 0 xp

### ISSUE THREAD

**Issue by Tsukaaaa** [Nader-Sl/Hackemon#116]
The bot can find pokestops, catch pokémons, snipe them too, but when it reaches the pokestop, it gives me 0 xp and it stops there, anyway to fix it?

**Comment by oOBlueArrowOo** [comment]
softban

**Comment by Tsukaaaa** [comment]
even if i can catch pokemons? they don't flee

**Comment by fcfidel** [comment]
no same thing happened to me

just wait  a few hours

**Comment by Tsukaaaa** [comment]
oh ok ty
