### ISSUE TITLE
"Our servers are humbled by your incredible response" - Fix

### ISSUE THREAD

**Issue by thorclaw** [Nader-Sl/Hackemon#119]
I think i figured out a way to solve this problem (if you are not banned).

Force stop Pokemon on your app manager.
Clear data
Uninstall
Go to APKMirror and download the 0.31.0 version of POGO 
Install - Open - And login to your account.
It will force you to update version, after it logs you in.
Go back to APKMirror and download the latest version (Don't log out the previous installation)
Install and open POGO.

Problem solved.

**Comment by kipperjx2** [comment]
really though????

**Comment by yoyos** [comment]
So you had this error ingame but the bot was still working, right ?
