### ISSUE TITLE
Pokemon flee but Pokestops work fine

### ISSUE THREAD

**Issue by Mxrs** [Nader-Sl/Hackemon#121]
Been doing this for a few days and its been working fine, I have the same co-ordinates as where I am in the game and have been levelling up quick and getting lots of stardust!

One thing which happened about 12 hours ago from this post is that Pokemon all flee; on the bot and manually.

Some people said this is a new soft ban Niantic implemented? If so does anyone know how long it lasts? Also if I just change co-ordinates and move on the App itself then re start the bot it works for about 60-100 Pokemon then 'breaks' again?

How can they detect this? Am I doing something wrong?

I have the settings on: 
Bicycle, Road Cycle, 74 KM/H
and then left all the other settings how they were.

Please help with this asap. Thanks :)

**Comment by jackjclarke** [comment]
74Km/h is defiantly not a realistic cycle speed... especially when you are gaining way more xp and pokestops/catching pokemon than someone who is at walking speed. Adjust the speed to 3-8km walking.. Also dont run the bot for hours on end, take interval breaks like you would if you were actually playing it legit

**Comment by Mxrs** [comment]
@jackjclarke 
Oh, right okay. I didn't really want to change the settings much but yeah that makes sense.
Thanks!

**Comment by jackjclarke** [comment]
It'll definitely slow the xp gain down.. but I've gone 0-23 in 5 days and not a single soft ban or anything

**Comment by Mxrs** [comment]
@jackjclarke 
That's okay, I'm level 30 now so just farming XP and stardust!
