### ISSUE TITLE
Bot not working (Accepting any level rewards.)

### ISSUE THREAD

**Issue by twk4924** [Nader-Sl/Hackemon#122]
it bot working on my win7 64bit

but dint work on my win8 64bit pc
after login , the bot show me Accepting any level rewards. 
and do nothing on there......

any solution to fix it???

**Comment by palmerd1603** [comment]
Why don't you run in under win7 compatibility settings?

**Comment by twk4924** [comment]
how to do that? can you teach me??? please

**Comment by palmerd1603** [comment]
Bear with me. I have used Windows in years.  Right click on the file, click properties, and look through the tabs in the window that pops up. It should be under the compatibility tag if I recall correctly.

**Comment by hdc29** [comment]
Not working on Mac either, saying the "Accepting any level rewards."  but doesn't do anything

**Comment by bugman840** [comment]
just fixed this issue delete filese and re-extract the zip folder
