### ISSUE TITLE
atempting to relog

### ISSUE THREAD

**Issue by ISeishiro** [Nader-Sl/Hackemon#124]
the bot is working fine. but after a few minutes, maybe 5 or so. it always attempts to relog then do stuffs again. its weird bcoz it is consecutively doing attempting to relog. any ideas why its like that? thanks.

**Comment by 13rentt** [comment]
I had the same issue. Go to settings -> Humanizer ->look for device info -> press **"Generate"** -> log in and run like normal. also don't forget to change your exploration radius to -1.

**Comment by ISeishiro** [comment]
ohh thanks for the info. :)
