### ISSUE TITLE
Max pokemons to catch and Max pokestops visited

### ISSUE THREAD

**Issue by xroginhox** [Nader-Sl/Hackemon#127]
Good afternoon you could add 2 new options to the bot? place the option: Max Pokemon to catch and Max pokestops visited after this number the bot automatically stop first catch Pokemon and after visiting the pokestops and disconect. Thanks for the excellent bot !!

**Comment by fuckNIANTIC** [comment]
yes! i agree with that, would be nice if you can have a trigger to stop once limit is reached. There has been news going on that Niantic is banning people who has capture more than 1000 pokemons and 2000 stops visit per 24hours. Please would be nice if we can set the capture and pokestop rate, thanks.

**Comment by frodo024** [comment]
This would be great!! I can confirm that news, for pokemon anyways. Pokemon would run after first throw but I could loot pokestops and interact with gyms. Every hour it would be lifted but as soon as i caught a few it did the same thing. Waited 24 hours and it was all better. Yes around 1000 pokemon per 24hours

**Comment by tranngocanh01071995** [comment]
I totally agree with you guys, this is necessary
Under 1000 pokemons and 2000 stops visit daily or get banned
