### ISSUE TITLE
Was working, now successful log in, but nothing happening?

### ISSUE THREAD

**Issue by stuc188** [Nader-Sl/Hackemon#129]
Any ideas please guys? Poke stops not loading up and the bots not moving, I'm fully logged in ok.

**Comment by MikeyFender** [comment]
Banned maybe, or check it out try to log in with your phone.

**Comment by stuc188** [comment]
I'm not banned buddy. It's working on my phone ok. Been out to my local poke shop and gym and its all working ok. Just the bots not loading anything up. It's all logging me in ok.

**Comment by rjelstyx** [comment]
same issue here.. i can only access pokemon tab but the bot tab is completely not working..

**Comment by bugman840** [comment]
just fixed this issue delete filese and re-extract the zip folder

**Comment by stuc188** [comment]
bugman.. yes. thats has fixed it thank you!

**Comment by stormcch** [comment]
@stuc188  how you fix it , i re-extract the file , it wont work for me .... 
my porblme same as you , stuck at login success !
