### ISSUE TITLE
Can't load on mac

### ISSUE THREAD

**Issue by littlegoodmidget** [Nader-Sl/Hackemon#13]
When i did the java -jar ect it said this p.s the ****** is just private stuff

****-***-***:~ ******$ java -jar /Users/*****/Desktop/Hackemon-master/Hackemon.jar -Xms512 -Xmx2048
Exception in thread "Thread-5" java.lang.NullPointerException
	at salt.hk.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
htmlFile: /html/maps.html

**Comment by SahilNair** [comment]
Uninstall Java, Install Java 8, set Java in path, Restart PC, Run run.bat, Run Hackemon.jar

**Comment by SahilNair** [comment]
Uninstall Java, Install Java 8, set Java in path, Restart PC, Run run.bat, Run Hackemon.jar

**Comment by Bonjur** [comment]
Uninstall Java, Install Java 8, set Java in path, Restart PC, Run run.bat, Run Hackemon.jar

**Comment by littlegoodmidget** [comment]
on mac @Bonjur

**Comment by Bonjur** [comment]
"for mac users here is what i did:
run run.bat with terminal
then drag jar to terminal(notsure)
then run hackemon.jar"

**Comment by colaz974** [comment]
grey screen anytime ...
