### ISSUE TITLE
Still a grey screen

### ISSUE THREAD

**Issue by Mxrs** [Nader-Sl/Hackemon#130]
Had the grey screen issue a a few days ago, somehow fixed it but now it is worse than ever.

Whatever I do it still goes to a grey screen as soon as I open hackemon.jar

It's never been this bad..

**Comment by MikJohnson** [comment]
**Possible Mac fix.** 
Install Java SE Development Kit 8u101 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
You may need to restart you're system.

After you've done this, and nothing is working, try open the program with Terminal;

Open Terminal
Copy/Type in: `Java -jar (Drag Hackemon.jar here) -Xms300m -Xmx1200m`
Hit enter and it should work.

**Comment by fyooree** [comment]
Have the same issue.

Everything is installed:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Any clue why it isn't working?
htmlFile: /html/maps.html

Thats everything I get ;)

**Comment by FixTechToday** [comment]
@fyooree The error: `htmlFile: /html/maps.html` is an familiar problem.  You may have to delete every thing of the "Hackemon Bot". After you've done this, make sure you have the right Java version. Then follow my steps I've posted earlier again.
