### ISSUE TITLE
what is the BEST setting for humanizer.

### ISSUE THREAD

**Issue by darellv** [Nader-Sl/Hackemon#131]

**Comment by outtasync** [comment]
I have mine set to Fast Human, 4 or 5km.h.  Road walk, and 1 meter noise.   Then I have the delays set to 3000ms to 5000 ms ball throw delay, and 3000ms to 7000ms Encounter delay, with a 50% curve reduction factor, and a 30% pokemon fail catch attempts.

I dont even know what breaks handler does.
