### ISSUE TITLE
Grey screen and the APPLICATION IS NOT RESPONDING

### ISSUE THREAD

**Issue by darellv** [Nader-Sl/Hackemon#133]

**Comment by xSamir123** [comment]
Im having the same problem too

**Comment by MikJohnson** [comment]
Same here

**Comment by Noah989** [comment]
Once I open it there is a grey screen and when I go to force quit it. It says that it isn't responding

**Comment by MikJohnson** [comment]
@Noah989 Are you using an mac?

**Comment by Noah989** [comment]
Yes

**Comment by Noah989** [comment]
do you need to update anything? eg Java

**Comment by MikJohnson** [comment]
You need java 8 update 101

**Comment by MikJohnson** [comment]
After you've done this, and nothing is working, try open the program with Terminal.

1. Open Terminal 
2. Type in: `Java -jar (Drag Hackemon.jar here) -Xms300m -Xmx1200m`
3. Hit enter and it should work.

**Comment by Noah989** [comment]
okay i'll try

**Comment by Noah989** [comment]
It still says not ressponding is the terminal code correct 
/User/ -- MyName --/Desktop/Hakemon-master/Hackemon.jar -Xms300m -Xmx1200m

**Comment by Noah989** [comment]
Its still opening with 
Jar Launcher (default) (15.0.1) is that the right update

**Comment by FixTechToday** [comment]
It looks like you've forgot 'Java -jar'

**Comment by FixTechToday** [comment]
And yes, the Jar launcher is a goor version. Doesn't it work after you've entered the code?

**Comment by Noah989** [comment]
Yea sorry I put the Java -jar in before the User
and yea still comes up with a black screen and says not responding when i look to force quit it

**Comment by FixTechToday** [comment]
So you still got the "Gray Screen"?

**Comment by Noah989** [comment]
Yea so what happens is when I click to open it a grey screen opens the exact same size of the actual bot screen and after about 15 seconds the it somes up on the force quit screen as not responding. 
The V1.5 worked for me but as soon as the V1.6 was released I have been having this problem. 
I have now tried it on 2 computers

**Comment by Noah989** [comment]
![screen shot 2016-08-20 at 12 35 15 pm](https://cloud.githubusercontent.com/assets/21073377/17828369/9bb010e6-66d2-11e6-9799-3835eee2867e.png)
this is what it looks like

**Comment by FixTechToday** [comment]
There are indeed more problems with V1.51 and V1.6. Can't you use the bot at all at the moment, or do you still have an back up from V1.5?

**Comment by Noah989** [comment]
Sorry I think that I was using the V1.51 and no nothing works I dont get any visuals apart from that

**Comment by FixTechToday** [comment]
And you're having problems with V1.6 as well?

**Comment by Noah989** [comment]
Yes I was having problems with the V1.51 late last night Sydney time and now having problems with the new version. The grey screen was occurring with both of them

**Comment by FixTechToday** [comment]
Ok, so V1.5 is working fine for you?

**Comment by Noah989** [comment]
I am not sure which version it was, I downloaded the version on 18th mid-day Sydney time and that worked well. Until last night when I could no longer open it and am having the problem I am now

**Comment by FixTechToday** [comment]
And do you have the same file that worked fine for you. I'm using V1.5 at the moment, not because the newer versions are not opening, but because there are unstable builds.

**Comment by Noah989** [comment]
no I put it in the trash and deleted it

**Comment by FixTechToday** [comment]
Do you need the old one? I've got back ups from all the versions.

**Comment by Noah989** [comment]
That would be great. It might also help you to see what is wrong with the current version if I can use it, I don't know. but a stable version would be good

**Comment by FixTechToday** [comment]
https://www.dropbox.com/s/qkpoagsd1v3zk5u/Hackemon%20V1.5.zip?dl=0

This is version 1.5. If this doesn't open for you as well by just double clicking `Hackemon.jar` Try to open is via Terminal.

**Comment by Noah989** [comment]
Just one idea you should offer updates some how soon the new version will be as close to bug free as possible. IDK I just think it would be helpful. Thanks for the link

**Comment by FixTechToday** [comment]
No problem, sadly doesn't the newer versions work for you, but V1.5 actually has the essentials for a bot.

**Comment by Noah989** [comment]
You won't believe it this version doesn't work either. Is there a way that I can erase all traces of the bot incase I have corrupted a file

**Comment by Noah989** [comment]
:'(

**Comment by FixTechToday** [comment]
Have you tried to open it using terminal?

**Comment by Noah989** [comment]
ill try again now

**Comment by FixTechToday** [comment]
I realize I've forgot to ask you a REALLY important step.

Make sure you've restarted you're Mac. Otherwise the Java update will not work!

**Comment by Noah989** [comment]
HAHAHA I'll check now

**Comment by FixTechToday** [comment]
After you've done this try the steps I've told you earlier again with maybe the newer versions.

**Comment by Noah989** [comment]
yea the V1.5 is working. Should I check the V1.6?

**Comment by Noah989** [comment]
okay its working now thanks

**Comment by FixTechToday** [comment]
I'm sorry I didn't ask this earlier, even I've told this in my tip I've posted earlier. But glad I've been able to help you.

**Comment by Noah989** [comment]
Just a tip a cool feature would be being able to sort your pokemon in different orders

**Comment by Noah989** [comment]
but thanks again

**Comment by FixTechToday** [comment]
That would be an great future indeed.
