### ISSUE TITLE
Crashes after 1 hour

### ISSUE THREAD

**Issue by FixTechToday** [Nader-Sl/Hackemon#135]
Like the title says, the new version and version 1.51 are crashing after one hour. It says that its re-loging, and just freezes.

**Comment by Mrwhononumber** [comment]
same here ..

**Comment by MikJohnson** [comment]
Version 1.5 worked fine for me. Until version 1.51 and 1.6 came out.

**Comment by VXT108** [comment]
same

**Comment by maxlehot1234** [comment]
Same here, but crash after few minutes....

**Comment by twk4924** [comment]
same here 
relogin and not working anymore

already did check login via phone
not solfban or perma ban

**Comment by maxlehot1234** [comment]
For me too, always try to re-login, but it works fine in others bot. Good buy hackemon...
