### ISSUE TITLE
Not catching pokemon nor getting items from poekstop in 1.6 upgrade!

### ISSUE THREAD

**Issue by Angerofpain** [Nader-Sl/Hackemon#139]
Sir, latest 1.6 upgrade is not capturing any pokemon neither is getting any items from pokestop....Only 50exp is obtained from pokestop but not items....up to 1.5 version was running perfectly....i tried running 1.6 in my another laptop but same issue.....hope you correct this bug with god speed....thanks for this app!

**Comment by rjelstyx** [comment]
check your items maybe full

**Comment by Angerofpain** [comment]
oops....thanks a lot :)..its  working now....

**Comment by jamielee181** [comment]
same here I'm getting items and XP but its not catching any pokemon at all
