### ISSUE TITLE
Bad pokemon name/pokemon name BIG ISSUE

### ISSUE THREAD

**Issue by maxlehot1234** [Nader-Sl/Hackemon#141]
![image](https://cloud.githubusercontent.com/assets/5159244/17828469/b6a4a49c-6660-11e6-82bd-db3fd0070412.png)
Hi, could you explain to me, why I get this with 1.6 version?

Thanks and maybe an option to class pokemon by CP, IV, name, etc will be awesome.

**Comment by ISeishiro** [comment]
lol. this is funny
