### ISSUE TITLE
Gained 0 XP

### ISSUE THREAD

**Issue by jeffhuang5550** [Nader-Sl/Hackemon#144]
I can't get any items from the PokeStop and also no XP earned from them.
Something like this:

Walking to the next pokestop at..............
Gained 0 XP

It is continuing getting 0 XP from every PokeStop and my bag is not even full...

**Comment by CrystalEcho** [comment]
Are you getting items while spinning pokestops? If not you maybe softbanned.

**Comment by fumikoBB** [comment]
same here~~just keep walking, no pokemon @@

**Comment by CyberLykan** [comment]
Softban. Wait a few hours and try again.
