### ISSUE TITLE
Items/pokemon refreshing a lot during the running, flash between 0 and number

### ISSUE THREAD

**Issue by Rommel-holmes** [Nader-Sl/Hackemon#145]
And get to pokemon tab, it flashes a lot too.

**Comment by romerey11** [comment]
This happens when the auto egg incubation is enabled. The refresh problem also causes the movement to be very slow.

**Comment by rjelstyx** [comment]
login to NOX, hatch the eggs, back to bot with incubation disabled.. it has issue with pokemon hatched..

**Comment by rjelstyx** [comment]
reply here to confirm if it works
