### ISSUE TITLE
"Attempting to Re-log" not ban-safe

### ISSUE THREAD

**Issue by angelo149** [Nader-Sl/Hackemon#147]
Hi,
I'm using v1.6.
2-4 times per hour the bot needs to re-login to my account. (I hope that's normal.)
While watching that procedure I noticed that Ash snaps back to the origin location from the general settings and starts his walk from the beginning.
Imo it's very unfavourable to prevent beeing flagged/banned.
Depending on the exploration radius set, some kilometers in just a second is the possible result.

I suggest to add a function by which the last position is saved every X seconds.
Maybe depending on path traversing speed?

All in all I really appreciate Hackemon and I hope you keep going!

Greetings from Germany.

**Comment by KillFacePT** [comment]
The last position would be a great feature

**Comment by josete2k** [comment]
Yes, I've traveled 2km in a few seconds... 

In 1.6 news are the last location as a new feature... But it doesn't work.

**Comment by josete2k** [comment]
Permabanned :(
