### ISSUE TITLE
 catch failed, soft banned?

### ISSUE THREAD

**Issue by cirios** [Nader-Sl/Hackemon#148]
Whit the new version I found this:
[02:10:32] [Pokemon Farm] Attempt failed [CATCH_FLEE]  Pokemon Catch Error, most porbably you are exceeding the request limit or soft banned :(.
What I can do?

**Comment by wintermute0001** [comment]
increase the time delay.  The API is rate limited and exceeding the rate causes this.

**Comment by outtasync** [comment]
Thats the default message.  I will get that, and then the next one will catch.

I have the Ball throw delay set to 3000ms to 50000 ms, and the encounter delay set to 3000 and 7000 ms.

so far so good.  I also have the reduction factor for curves set to 50%, the highest it can go. 

Mainly im using this thing to walk egg off and catch random pokemon and hit stops on the way.   I dont need 210 xp per catch, Im fine with 100 to be honest.
