### ISSUE TITLE
Max OSX Freeze

### ISSUE THREAD

**Issue by littlegoodmidget** [Nader-Sl/Hackemon#15]
so when i do 
java -jar Hackemon.jar -Xms512 -Xmx2024 it says this  **** are private stuff

/Users/*****/Desktop/Run.sh ; exit;
*****:~ *****$ /Users/*****/Desktop/Run.sh ; exit;
htmlFile: /html/maps.html

**Comment by tolinwei** [comment]
Similar situation, when I do `$ Java -jar Hackmon.jar -Xms300m -Xmx1200m`, it says `Error: Unable to access jarfile Hackmon.jar`, even after setting `chmod +x Hackmon.jar`,

If I run `./Run.bat`, it opens a window with nothing inside. 

macOS.
