### ISSUE TITLE
NOT CATCHING POKEMON/SNIPE FEATURE DONT WORK

### ISSUE THREAD

**Issue by jamielee181** [Nader-Sl/Hackemon#150]
the Bot seems to not catch any pokemon and when i use the Snipe feature it says pokemon could not be found. Only issue i have had since the new update v1.5 everything worked fine

**Comment by frodo024** [comment]
Are you sniping verified pokemon?

**Comment by jamielee181** [comment]
im sniping pokemon that i were sniping on patch 1.5. plus the bot dont even catch pokemon anymore

**Comment by DratiniDragon** [comment]
This is the same as issue #125 . Read through #125 instead

**Comment by jamielee181** [comment]
that dont help idk why they updated it they have made the bot shit not nothing works anymore they need to fix it
