### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by iOwnThis** [Nader-Sl/Hackemon#152]
![hackemon](https://cloud.githubusercontent.com/assets/21142088/17831371/327f8178-66e7-11e6-8977-ae48f220bf13.PNG)

any ideas?

**Comment by KillFacePT** [comment]
Try to erase everything and download again

**Comment by rjelstyx** [comment]
login to NOX, hatch the eggs, back to bot with incubation disabled.. it has issue with pokemon hatched..

**Comment by rjelstyx** [comment]
reply here to confirm if it works

**Comment by scooterbelasco** [comment]
If you have that screen, just right click on the background (white area) and seclect 'Reload Page'

**Comment by rjelstyx** [comment]
try my method.. now my bots work..

**Comment by frodo024** [comment]
That happed to me when my router got unpluged and i lost internet
