### ISSUE TITLE
Does the sniper function work?

### ISSUE THREAD

**Issue by ShupengHu** [Nader-Sl/Hackemon#154]
Never try it. Anyone try snipe pokemons?

**Comment by wintermute0001** [comment]
sniping will get you banned.

**Comment by frodo024** [comment]
I have not seen anyone banned yet from sniping.

**Comment by wintermute0001** [comment]
sniping is the primary reason for getting banned.  see [here for a long chain of field reports](https://github.com/PokemonGoF/PokemonGo-Bot/issues/4114).  

Also, logically, sniping is the easiest thing to detect.  If a player's position changes in a way that violates the laws of physics, then they aren't playing legally.

**Comment by DratiniDragon** [comment]
Sniping works well but beware only use it for up to an hour at a time. If you exceed this limit or snipe too often (only snipe one pokemon every minute or so) the bot won't find any normal pokemon and the sniping feature will fail to find the pokemon you are looking for. I believe this is some form of ban, although it does lift quite quickly. I haven't seen anybody banned from sniping either, and you should try it, its very effective. I have sniped many times and have received probably 30+ softbans, and Niantic still haven't banned the account. ALSO, if you don't want to get banned, if any form of suspicious/ban like behaviour is detected on an account which is Lvl 30+, it will be permanently banned almost straight away - so be careful.

**Comment by wintermute0001** [comment]
They don't ban accounts under level 20.  But as soon as you're above 20, it's only a matter of time.  If you're above 30, you're guaranteed.  

If you ever plan to hit these levels, then you can't snipe.  Niantic doesn't erase data from earlier levels... 

Also, that's weird you haven't seen it.  There's been numerous field reports that tested this hypothesis.

**Comment by RiberoD07** [comment]
just think about it logically. they just do a cross reference check from where and when a pokemon was encountered and when and where the pokemon was caught, obviously it's not going to be humanly possible in 99% of cases and thus your account will get get flagged and 100% banned. Why do something that unnecessarily risks the account?

**Comment by outtasync** [comment]
I sniped a ton on an account, and it was banned.  I sniped a few on another account, and it was banned.

When it came to running a bot, I would run in, say, the Santa Monica Pier, and then nothing overnight before I logged in on my phone.  I was cautious with everything but sniping.

Sniping is dangerous.   Do it at your own risk.
