### ISSUE TITLE
Can you turn off curve balls?

### ISSUE THREAD

**Issue by jprz037** [Nader-Sl/Hackemon#155]
Is there a way to turn off curve balls and how can I increase the chances of fail catches. I put it at 90% and it still catching all pokemon.

**Comment by DavidSelem** [comment]
If you want to disable curve balls, open settings.json with notepad and find this "enableCurveBall":true," change it to "enableCurveBall":false,"

**Comment by jprz037** [comment]
Where can i find settings.json? Im using linux and i cant find it.
