### ISSUE TITLE
No pokestops

### ISSUE THREAD

**Issue by ivanengler** [Nader-Sl/Hackemon#156]
When I start the bot, it doesn't do nothing, just stay there. I'm not banned, on nox is normal. Anyone knows how to fix it ?
![0ekurl7](https://cloud.githubusercontent.com/assets/21036402/17832047/92edf812-66d0-11e6-80b8-70ed821dd84b.png)

**Comment by wintermute0001** [comment]
try deleting the settings.json and reopening

**Comment by ivanengler** [comment]
@wintermute0001 Worked perfectly, thank you man!

**Comment by wintermute0001** [comment]
awesome.

@Nader-Sl  --- this is a bug; not sure what's causing it.
