### ISSUE TITLE
Resizing does not resize UI.

### ISSUE THREAD

**Issue by CyberLykan** [Nader-Sl/Hackemon#157]
As seen in this picture below.
![screenshot 9](https://cloud.githubusercontent.com/assets/21145060/17832598/9f8d927a-66cc-11e6-942e-c0fbcc8d1b43.png)

**Comment by daisukeDan** [comment]
i hope that resize ui when resizing window :)

**Comment by CyberLykan** [comment]
To clarify, when window is resized manually or w/ buttons, the user interface does not resize as well, resulting in a gray background behind the original user interface.
