### ISSUE TITLE
bug with pokemon items and pokeballs

### ISSUE THREAD

**Issue by greyjester** [Nader-Sl/Hackemon#159]
heres a few screen shots of what its doing http://prntscr.com/c884cn 
http://prntscr.com/c885bt
http://prntscr.com/c8852c

the last screen shot is the true one

**Comment by josete2k** [comment]
Me too. 

I can't manage pokemon too. Well, I can manage them but they are switching up/down every time.

**Comment by rjelstyx** [comment]
Bot have issue with hatched egg.. Don't use incubator when running hackemon..
