### ISSUE TITLE
Won't collect items from PokeStops

### ISSUE THREAD

**Issue by Shofstall** [Nader-Sl/Hackemon#16]
It'll run and when it reaches 0 Pokèballs, it just walks around. How can I make it farm PokeStops for items?

**Comment by stormcch** [comment]
ya
i have this problem too
i think it need pokeball in inventory , so the bot will work like a normal 
lol 
prOblem not fix yet , 
so you need to log in your account , and go pokestop your self , collect maybe 100 ball
and run the bot back , it will work like normal 
PS : still trying !

**Comment by Shofstall** [comment]
Any fix?
