### ISSUE TITLE
egg hatching / incubator does nothing

### ISSUE THREAD

**Issue by warchucky** [Nader-Sl/Hackemon#160]
i dont think the egg hatching/incubator is working in 1.6
it does not show anything in the log and i'm never pinking up any eggs at pokestops, so i dont think it is working.

**Comment by frodo024** [comment]
I think it will start them if there is none incubating, but it will not accept them after they are done. So you
Have to log in on phone and accept.

**Comment by outtasync** [comment]
Id like to see an option for picking which eggs incubate....2km, 5km, or 10km.  Simple checkboxes would be great.

Im saving my 10s for when I am higher level

**Comment by mkimid** [comment]
If just use the default incubate for 2km or 5km, and 10km for the temporary (3 times) incubator. 
I will be best, also, 
or just use the default incubator option.
