### ISSUE TITLE
Accepting any level rewards stuck

### ISSUE THREAD

**Issue by matyextreme** [Nader-Sl/Hackemon#163]
I'm stuck on this message
 [00:00:08] Accepting any level rewards.
Does anyone knows how to fix this? I am running the bot in a mac

**Comment by eakmitree** [comment]
try to change the startup lat, long. Its work for me

**Comment by matyextreme** [comment]
thank you 👍 actually I believe it was an ip error because I used vpn and now it's working properly (without the poke sniping feature)

**Comment by SwoleSnorlax** [comment]
same error, however changing lat and long doesn't fix it.

**Comment by logan5171** [comment]
Same here for over 24 hours ago :-S ....any suggestions?

**Comment by ivanpermana** [comment]
Delete the hackemon first, then extract it again from Zip File. Just re-setting it again and start. It works for me here. (Sorry my english bad)

**Comment by logan5171** [comment]
nice!!!!!, problem solved!!, thanks ivanpermana
