### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by audiostar** [Nader-Sl/Hackemon#167]
![alert](https://cloud.githubusercontent.com/assets/21151930/17835578/7b5e194a-6773-11e6-949d-e66e365d6b00.jpg)

im getting this in cmd, 
when i press start, im logged in but it doesnt go further.

any idee`s? yesterday it worked fine

**Comment by rjelstyx** [comment]
Login to nox.. Check if you have hatched eggs..

**Comment by Yorickvdg** [comment]
I have the same alert, and in the console : Accepting any awards

normally that moment the pokestops disappear! I have a new virtual machine installed and it was working agian. But when i was done with pokesniper and want it to bot again i got the error.

I think becouse the last saved long en and lat becouse in v1.15 i had no errors.

**Comment by audiostar** [comment]
i hatched mine eggs out, and i dint put it on in settings,

**Comment by audiostar** [comment]
Deleted everything and then put it al back and it worked again.

**Comment by ggebler** [comment]
what have you deleted? is the hatching egg working?
