### ISSUE TITLE
Ultra Ball and Great Ball

### ISSUE THREAD

**Issue by kadaro90** [Nader-Sl/Hackemon#169]
Hey.
Is is possible that the bot uses ultra balls and great balls in the first place to catch pokemons? I lost all of my ultra balls and their not on the list of items to recycle. Didn't catch anything special neither… Can it be somehow set which pokeballs to use?
Thanks

**Comment by givecoinsupport** [comment]
When set an auto recycle option, i feel it recycle all ultra ball even there is no list. I lost 270 ultraballs, and now I have disabled auto recycle option
