### ISSUE TITLE
Exploration radius not working correctly?

### ISSUE THREAD

**Issue by Siedjeey** [Nader-Sl/Hackemon#171]
I am farming in a spot with lots of rare pokemon but don't want to wander too far off but somehow the exploration radius does not seem to work properly? I tried lowering it to 100 meter but i always keep walking to that far off pokestop which takes a lot of time and is way off the farming spot...

Is is impossible to stay in one spot and just farm the pokestop every 5 minutes and catch all the pokemon that appear?

**Comment by tucoh** [comment]
i'm having a similar problem, i've even tried the -1 radius to explore everywhere, but the bot seems to only go back and forth between a couple of pokestops?

**Comment by Siedjeey** [comment]
Yeah it's pretty annoying tbh, I prefer catching Pokemon at the rare locations than running all over for Pokestops...

**Comment by bstana** [comment]
@tucoh Try 50 meters exploration radius. Worked for me.

**Comment by Siedjeey** [comment]
Doesn4t seem to work for me at any distance setting. And putting 0 also doesn't stop from moving at all.
