### ISSUE TITLE
Cant log in with google account

### ISSUE THREAD

**Issue by jprz037** [Nader-Sl/Hackemon#175]
I cant log in with google account but i tried with ptc and it does work. Im 100% sure the user name and password is right because i logged in gmail and it logged me in.

**Comment by DratiniDragon** [comment]
For google accounts, you need to use the email linked to the account rather than the username. Put your email and password, not your Pokemon GO name.

**Comment by jprz037** [comment]
I think its because of 2 step verification. I succesfully logged into one without it.
