### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by mgiio** [Nader-Sl/Hackemon#180]
![hackmon bug](https://cloud.githubusercontent.com/assets/21158297/17838357/f1f5ef3a-67cb-11e6-8fc3-c759c7442870.jpg)
When I put start ( with already placed coordinates, email, password ...) don´t work, the last message that puts me in the feedback is " Succesfully Logged in with your Google Account (************************), but the character does not move, also are not visible PokeStops, neither are not visible statistics...
As if frozen.
It is something of mine or some kind of bug?
PD: Before working

**Comment by maarteNNNN** [comment]
I had the same problem, you switched to another location too fast, pokemon is detecting your spoofing, go back to your location where you last had pokestops and you should be good.

**Comment by Huntedza** [comment]
Have the same problem as OP. After I set everything up the I started the bot, but it did not change my location as i set it. It was on the default location.

Realized that and the stopped and closed the bot and opened it again. After that it picked up my location just fine. However the pokeguy is just standing in one spot.

Also do you need to have you location settings in Windows set to off?

**Comment by mgiio** [comment]
Dunno, I tried but still like before.
I did wait some time for teleport to another site like a human to make it look real.
I did that some times and i don´t had this problem, I think its a bug or dunno...

**Comment by batoto05** [comment]
same here it just freeze there bfore this nvr change coords just now decide to change it and it freeze there last msg was accepting lvl rewards ==''''

**Comment by pimpinbitchesontheregular** [comment]
Yeah - this happens now and again - just make sure you're not using an app on your device that uses location services. Kill all apps that are running in the background that use it. Hey presto!
