### ISSUE TITLE
sniping not working

### ISSUE THREAD

**Issue by maximus123456** [Nader-Sl/Hackemon#19]
sniping is not working

**Comment by FumaWeed** [comment]
I think the snipe could be a major cause of permanent bans, perhaps serve not work. Although I could not tell you

**Comment by CrispyBaconUk** [comment]
Sniping is working, its just the source server is down - should switch to pokezz

**Comment by maximus123456** [comment]
can we switch source server? or we have to wait for the developer?

**Comment by wEisB0145** [comment]
same for me.... how do you switch the server w/o manually sniping?
