### ISSUE TITLE
Egg incubation and Hatching egg not working

### ISSUE THREAD

**Issue by ggebler** [Nader-Sl/Hackemon#191]
Even the option been flagged, the automatica egg incubation and hatching egg reward are not working... Should I do something else beside flag the option?

Greetings!
![untitled](https://cloud.githubusercontent.com/assets/21113239/17840328/fbd73e56-67d9-11e6-8bfd-f56cfadf2a69.png)

**Comment by ggebler** [comment]
someone else having the same issue?

**Comment by nightwal** [comment]
me too

**Comment by Driesboy** [comment]
it work for me
