### ISSUE TITLE
DUPLICATES ISSUE

### ISSUE THREAD

**Issue by GuessWhoMe** [Nader-Sl/Hackemon#192]
Let's say I have a low cp and iv of horsea with me. I always set my duplicates to keep to 1. However, when  my hakemon catches a new horsea, it then transfer both the newly catch and my old one. It ends up I don't have any horsea in my inventory. What do I do?

![image](https://cloud.githubusercontent.com/assets/21163222/17840823/8e331cda-6842-11e6-84b0-80005df2b3c8.png)

Here is a screenshot of my current auto duplicate setting. Note that I am only level 9 if ever so the pokemon cp I catch isn't that high. Thank you! :)

**Comment by greyjester** [comment]
decrease your cp to the standard 1,000 at your level you won't be catching 1,800 cp pokemon this might fix it

**Comment by greyjester** [comment]
its you cp turn that down to 1000 and duplicates to 0 you should start gaining and transfering i had that problem with the Nidorina once i got it i went and evovled it in the evovle tab

**Comment by ggebler** [comment]
The loggical inside the duplicate to keep is to keep at least x pokes more than one you have which have the conditions... So, in ur case, you'll keep one more same kind Poké, ever since urs 2 pokes matchs the condition: neither over 1800cp or at least 80%iv
