### ISSUE TITLE
after recent mini patch 1.61 it wont open

### ISSUE THREAD

**Issue by ishort2205** [Nader-Sl/Hackemon#193]
![screen shot 2016-08-21 at 8 11 27 pm](https://cloud.githubusercontent.com/assets/21071353/17841257/59f02370-67dc-11e6-8f13-bd725c5a2b5b.png)

**Comment by ishort2205** [comment]
it has worked until new mini patch

**Comment by greyjester** [comment]
update your java maybe and don't use there security features for java had that problem

**Comment by ishort2205** [comment]
someone on discord sent me their setting.json and it works now thanks anyway

**Comment by BigRedCrayon** [comment]
Could you post the setting.json file please for everyone that has this issue?

**Comment by XitoAliferis** [comment]
can u send me or post the setting.json file please because i have the same issue
