### ISSUE TITLE
i can't open it

### ISSUE THREAD

**Issue by XitoAliferis** [Nader-Sl/Hackemon#195]
this error message pops up and i don't know what to do. Please help!
<img width="420" alt="screen shot 2016-08-22 at 12 04 05 am" src="https://cloud.githubusercontent.com/assets/15039480/17843437/0417c078-67fc-11e6-8aa4-f3ef09ea7bf4.png">

**Comment by shaneehlert** [comment]
same here i get the same thing now

**Comment by cre8tiff** [comment]
Mine was working fine. Until it starts re-logging in; and hung on its track. And now, restart attempts are showing a blank gray box. Mac. Have reinstalled oracle java 8; deleted temp files. Not working
