### ISSUE TITLE
#1.61 Non-stop "Attempting to Re-log"

### ISSUE THREAD

**Issue by ratel93** [Nader-Sl/Hackemon#196]
![hackemon_issue2](https://cloud.githubusercontent.com/assets/18246600/17844565/6ca372a6-686d-11e6-891e-9537af42005d.PNG)

**Comment by Driesboy** [comment]
fix your internet

**Comment by Nader-Sl** [comment]
this mostly means you are IP banned, i've added such a message on v 1.61, i don't think you were running 1.61 there after update you have to restart client so it takes effect.
