### ISSUE TITLE
Problem when launching

### ISSUE THREAD

**Issue by Yungtang** [Nader-Sl/Hackemon#198]
Hi,

I've downloaded the latest patch of Hackemon and Java JDK 8u102 and installed these on my two computer (MacBook Air and Mac mini) but when I try to launch Hackemon.jar, the app opens and stays on a grey window indefinitely... Is someone having the same problem and how to solve it please ?

**Comment by cre8tiff** [comment]
I got around this issue by replacing with the settings file shared by a discord user. However, the bot still doesn't work as it's supposed to after the repairs.

**Comment by Yungtang** [comment]
Can you send me the setting file tho ? :)

**Comment by cre8tiff** [comment]
There you go

**Comment by Yungtang** [comment]
There is nothing to dl :/

**Comment by cre8tiff** [comment]
Check your email?

**Comment by Yungtang** [comment]
Unfortunately nothing

**Comment by cre8tiff** [comment]
[settings.json.zip](https://github.com/Nader-Sl/Hackemon/files/429522/settings.json.zip)

**Comment by Yungtang** [comment]
Thanks a lot !

**Comment by Yungtang** [comment]
Still not working, but not the same problem...Saying that it's unable to launch the Java Jar File !

[hs_err_pid14256.txt](https://github.com/Nader-Sl/Hackemon/files/429529/hs_err_pid14256.txt)
