### ISSUE TITLE
Crashing on start up

### ISSUE THREAD

**Issue by Jinnocid** [Nader-Sl/Hackemon#2]
i installed java its still crashing do i need to install other stuffs?

**Comment by Jinnocid** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x000007fef0fdca90, pid=4696, tid=0x0000000000001850
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [msvcr120.dll+0x8ca90]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#

**Comment by Nader-Sl** [comment]
Re-install Java, remove, update to latest.

**Comment by Jinnocid** [comment]
just did it still having some errors idk whats happening
