### ISSUE TITLE
define limits of items

### ISSUE THREAD

**Issue by BombNuker** [Nader-Sl/Hackemon#20]
There should be an option to choose how much of each items we want so that the bot doesn't get stuck when he gets 350/350 of items. A minium and max for each item with a cycle when it surpasses the max would be awsome.

**Comment by BombNuker** [comment]
This is necessary because of the countage of great balls, ultra balls and razz berries

**Comment by maximus123456** [comment]
The author is MIA. is sniping working for u?

**Comment by BombNuker** [comment]
Nope :/ using 1.4 version

**Comment by maximus123456** [comment]
same D:

**Comment by FumaWeed** [comment]
Cuz u activating recycling leaves you with nothing to haha moment is not measured
