### ISSUE TITLE
Bot not collecting eggs and pokeballs

### ISSUE THREAD

**Issue by swangaa** [Nader-Sl/Hackemon#201]
The bot doesnt seem to collect eggs because my bot whose level 23 now has only 2 eggs.
it doesnt collect or save my pokeballs, great balls and ultra balls either

**Comment by Nader-Sl** [comment]
It does collect eggs, but it uses them, check the settings, it should be incubating them, it collects all rewards from pokestops, but there is a setting as of 1.61 on what balls to use and not to use based on xp

**Comment by Nader-Sl** [comment]
wait till next patch which will come with a guide, and re-open an issue if it didnt solve your problem
