### ISSUE TITLE
Bot only going to PokeStops

### ISSUE THREAD

**Issue by Raftoulis** [Nader-Sl/Hackemon#202]
Hello,
I setup the bot in an area of 5 pokestops which almost all day have lures, yet the bot fails to initiate capture with any pokemon. Basically it grinds the pokestops without doing anything else. Tried both Road Walk and Road Fly. Speed is 14km/h and obviously I have enabled auto pokemon catching. Explore Radius is about 100m so it stays within said pokestops.

Edit: It seems not to be able to count XP and Pokestop visits too.

Thanks

**Comment by Nader-Sl** [comment]
Increase range to further than 100, perhaps no pokemon is popping at the point, 100 is a small area, you should be able to get counts of pokestops and pokemoms, unless you are having some error i'd have to see what the log and cmd print out.
