### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by lastorder999** [Nader-Sl/Hackemon#203]
<img width="1680" alt="screen shot 2559-08-22 at 4 51 34 pm" src="https://cloud.githubusercontent.com/assets/19435992/17850745/ddd57ef4-6888-11e6-8d08-1febba60487e.png">

**Comment by maarteNNNN** [comment]
Do you have the right Java SDK? 
[](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by Nader-Sl** [comment]
I'll am aware of the mac problem, ill address as soon as i could.
