### ISSUE TITLE
grey screen

### ISSUE THREAD

**Issue by Jarhead6** [Nader-Sl/Hackemon#21]
typed in:java -jar /Users/dennis/Desktop/Hackemon-master/Hackemon.jar -Xms512 -Xmx2048 and get :htmlFile: /html/maps.html, and then hackemon.jar loads, but just get a grey screen, how can i fix?

**Comment by colaz974** [comment]
Same

**Comment by CrispyBaconUk** [comment]
Make sure you have Java SE Development Kit 8u102 - once I installed this it worked fine. However it crashed after a few hours and im back to the grey screen

**Comment by Jarhead6** [comment]
java se development kit 8 u 102 is installed but it won't work,
just grey screen

**Comment by itzcreamy** [comment]
same ^

**Comment by fcfidel** [comment]
is it on mac?


do this : 

right click on the hackemon.jar
get info
go to the tab that says: open with make sure it is set to : Jar launcher

close

right click on hackemon.jar 
open with jar launcher

enjoy :)

**Comment by CrispyBaconUk** [comment]
You do realise that will make 0 difference if you launch via termial or jar launcher? 
There are uncaught exceptions being thrown and it seems to be unstable on mac - very likely to be a jvm issue

**Comment by Jarhead6** [comment]
thanks fcfidel, it works :D

**Comment by colaz974** [comment]
Still grey screen after you do Fcfidel

**Comment by ciannaaperta** [comment]
Works like shit

**Comment by ciannaaperta** [comment]
on mac

**Comment by lastorder999** [comment]
same on mac
