### ISSUE TITLE
Recycling

### ISSUE THREAD

**Issue by rhyswford** [Nader-Sl/Hackemon#22]
why does it Always recycle my items and transfer my pokemon, also it will only let me be in Australia how can I change where it puts me?

**Comment by skoo1bag** [comment]
You have to set your Latitude and Longitude for you to change your location. 
(After setting, run the bot and it will automatically change your location to your desired location based on your Lat and Long)

The bot automatically transfers your items to prevent your bag from being full after farming pokestops,

Your pokemons as duplicates are useless.
