### ISSUE TITLE
Issues and Possible additional features

### ISSUE THREAD

**Issue by skoo1bag** [Nader-Sl/Hackemon#24]
Additional Features that could be added :

1) Saving new default location rather than staying on the same one to prevent teleportation
(When you reconnect, it teleports you back to the default location rather than the previous left off location)

2) Excellent catch off toggle 
(Currently every of my catch gives me 210XP which meant that I'm having 100% excellent rate. Possible to toggle this off to avoid suspicions?)

3) Disable auto route when next Pokestop is around 50m(Or toggable) 
(Rather than taking a gigantic route around to the next Pokestop which is nearby, the bot can just walk straight towards it) 

4) Drag circle
(In the map, we can drag a particular area for our character to walk around rather than wondering out to far locations with no pokestops)

Issues: 
1) Common Java issues where SE library keeps closing 
2) Sometimes it bugs out trying to repetitively go to a pokestop (Image attached)

Overall, good work! 
This is a wonderful bot! I can see loads of effort placed in and I hope to see more :D! 
Cheers!
![pokestop](https://cloud.githubusercontent.com/assets/17916212/17654034/e9de916c-62d0-11e6-9ed6-210d979dceb6.png)

**Comment by maxlehot1234** [comment]
1) Agree

2) Agree

3) Already exist, set road_fly into humanizer tab under google map route

4) Maybe a maximum rang so the bot always stay inside the circle to take the pokestops and pokemons

#38 


For your bugs, I have the same thing for the pokestop, . so the bot always try to take the same pokestop...
