### ISSUE TITLE
won't open on mac/ stuck on grey screen

### ISSUE THREAD

**Issue by reporting4** [Nader-Sl/Hackemon#25]
i have the latest version of java installed on my mac, it was working for the first few times but then everytime i tried to open the app, it gets stuck on a grey screen. anyone know how i can fix this?

**Comment by crucialfate** [comment]
i facing same problem as well

**Comment by Kundvagnsverktyg** [comment]
same

**Comment by littlegoodmidget** [comment]
I know a fix that does not include the terminal but id rather not say it possible p.s I got no idea if it still works in latest patch

**Comment by omare7** [comment]
Here is what worked for me opening it for 5 minutes then closing it for about 5 minutes do this around 4 or 5 times and eventually it will open trust me then it will update to the new version and the gray screen will be fixed
