### ISSUE TITLE
sniping not working anymore

### ISSUE THREAD

**Issue by crucialfate** [Nader-Sl/Hackemon#27]
Sniping rare pokemon stop hacking halfway suddenly and it has stopped for working until now, about 8 hours? will it be fix?

**Comment by pingpongplaya** [comment]
just found out about hackemon and started using this, not sure how auto sniping works but I tried sniping using coordinates after the first one it got me softbanned from catching pokemon. I was able to spin stops however. Any idea? thanks

**Comment by pingpongplaya** [comment]
had the softban lifted by throwing missing balls in game lol. tried the manual sniping with the updated v1.5. got softban again. so yeah, don't use that feature for now. autosniping also got disabled in v1.5

**Comment by DrakusX** [comment]
The manual snipe was working great in 1.4 would go and get every pokemon at the coords it found which was extra exp and it would bring back the specific one also. Now in 1.5 it says its going sniping comes back.. berry's it ... goes back to snipe it... berry's it... repeats over and over never catches or seems to try to.

**Comment by PokemonAddict** [comment]
worked for me in both versions. The rate, that the pokemon was there was 100% in version 1.5 - but was banned :(
