### ISSUE TITLE
Does not open Pokestops.

### ISSUE THREAD

**Issue by drumx** [Nader-Sl/Hackemon#30]
Well amazing bot but i can't use it, it says accepting any level rewards and does not auto walk or anything, also it does not show the pokestops, i can place the gps in my house but it just wont start to walk or show pokestops. any fix?

**Comment by pingpongplaya** [comment]
probably ip ban. try changing your up with vpn or resetting your modem

**Comment by PokemonAddict** [comment]
jep - banned - hard or soft. Did you snipe? Then maybe hardban

**Comment by Evertvaningen** [comment]
Never go full Snipe (┛◉Д◉)┛彡┻━┻

**Comment by drumx** [comment]
Im using another bot and works without a problem, i try different accounts and it does not load the pokestops, is not ip ban is not soft ban, i didn't snipe at all, i couldnt use it because it does not load pokestops so it does not move.
