### ISSUE TITLE
Better access to pokestops

### ISSUE THREAD

**Issue by maxlehot1234** [Nader-Sl/Hackemon#31]
Hi, I have found something weird:
![capture](https://cloud.githubusercontent.com/assets/5159244/17657611/c82911b6-6292-11e6-9fcc-bed3bc74626c.PNG)

Any way to found a better way to access pokestops to gain time ;)

It could be nice.

So sorry for the amount of tickets

**Comment by pingpongplaya** [comment]
use the road_fly setting...

**Comment by maxlehot1234** [comment]
Thank you ;)
