### ISSUE TITLE
No Pokemon

### ISSUE THREAD

**Issue by Nikilmista** [Nader-Sl/Hackemon#36]
I have let the bot run for about an hour, and all it has been doing is collecting pokestops. whenever i try to snipe it says, "could not find the pokemon". Also the pokemon farm hasnt caught any!

**Comment by maxlehot1234** [comment]
You are probably soft-banned

**Comment by Evertvaningen** [comment]
First thing is to copy your play style to the bot. Like speed 10Km/h
