### ISSUE TITLE
The ideal walking way!?

### ISSUE THREAD

**Issue by PokemonAddict** [Nader-Sl/Hackemon#37]
Tried a bot which calculated the optimal way for walking through all pokestops in the range but I guess this logic is missing in the bot. Also the bot could stop walking (eg. 1-30 sek) after a random walking way (eg 50-500m) and a bigger break after 30-90 Min.
What is confusing for me is the speed. Why is 35 km/h a "fast" human? But in the end it seems a normal speed on the map.

**Comment by Evertvaningen** [comment]
Mine walks 12Km/h
