### ISSUE TITLE
Improvements (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

### ISSUE THREAD

**Issue by Evertvaningen** [Nader-Sl/Hackemon#38]
# Improvements (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

I made this Issue post to (hopefully) group alle improvements for the future to make a convenient list for the developers.

1. When re-login let Hackémon remember the last GPS location or else it jumps back to the manual GPS location. This is Ban dangerous...

2. Log files would be nice.

3. A option to remember session scores 

4. Auto center map on player

5. Normal walker preset speed 12Km/h

6. Pokémon Gym icon on map

7. Bot taking breaks to rest

8. Open eggs 

9. Programmable GPS map router with Pokéstop scanner withing 10 meters of route. 
So you can route a route around the entire city and finish it at the beginning w8 (specified time) and do it again, and stops after 3 repeats :) Something like that would be Human as it can be. 

10. Recycle item delay time option

11. Who recycles 1x a item? this needs to be disabled. This behavior may be traceable 

12. Hackémon needs to remember it's custom speed, 100km/h is just too fast!
On program launch it still will have the GPS speed of previous session. 

13. Feature to start session on program launch 

◄ maxlehot1234 ►
1. Catching Rare Pokémons: Try with 1-2 pokeballs and if this not work, try with super and ultra pokeballs.

2. An option for incense: This could be useful to get pokemons and increase  

3. An option to keep Pokemons that have more than (amount specified) CP, so this could be very useful I hink to have an option to keep Pokemons that have more than 1500 CP for example.

4. Maybe an option to define a maximum radius. I know there is the radar meter. But something to prevent the bot to go away from a place.
EX: ^^ If I setup my pokemon in santa monica, I want it to stay near it of 500 meters, not more than this. For the moment, he can move to another pokestops if it was under than 500 meters fdrom the other one...

![Map](https://cloud.githubusercontent.com/assets/5159244/17666823/0c5eb6c8-62d0-11e6-9095-f699cbfdc3fb.PNG)

EDIT: 
Maybe an option in the stats panel to display all pokeballs types instead of just pokeballs

5. Is it possible to add soemthing to display the picture of pokemons we caught? It could be cool :)

**Question**: Why does Hackémon need to stand exactly on top of a Pokéstop?

**Comment by maxlehot1234** [comment]
YEEAAHHH and maybe something to set a maximum of pokeballs, like 150 and over this, they are simply deleted. This could be nice ;)

And maybe something for rare pokemons. Try with 1-2 pokeballs and if this not work, try with super and ultra pokeballs. Is it possible?

**Comment by maxlehot1234** [comment]
New ideas ;)

**Comment by wEisB0145** [comment]
Oh yeah and I have also an improvement: Allow max. 100 pokeballs in the inventory :)

**Comment by mickey101** [comment]
With the latest version (1.5) you can set up the maximum pokeballs to your choice at the items to recycle option.

**Comment by wEisB0145** [comment]
oh okay, thanks

**Comment by maxlehot1234** [comment]
Edit my suggestions ^^^

@Evertvaningen 
Add them on your subject so I can remove my comment to allow the dev to see them easier ;) at the same place

**Comment by Evertvaningen** [comment]
@maxlehot1234 
I no understand ˚⌇˚

**Comment by maxlehot1234** [comment]
@Evertvaningen 
I mean, add all my suggestions directly on your first post so the dev can see it directly ;) Because this threads become big, we have a lot of feature :P :P

**Comment by wEisB0145** [comment]
xD
rip developer

**Comment by Evertvaningen** [comment]
@wEisB0145 Why's that?

**Comment by maxlehot1234** [comment]
@Evertvaningen 
Is it possible to add soemthing to display the picture of pokemons we caught? It could be cool :)
