### ISSUE TITLE
Application Not Responding. [Mac]

### ISSUE THREAD

**Issue by Snarcasaur** [Nader-Sl/Hackemon#4]
Dear Nader-SI,

I have downloaded Oracle Java 8 many many times. And Each time I downloaded hackemon everytime I downloaded Oracle Java. And it keeps giving me the same response. Application Not Responding. Please help it is extremely annoying.

Sincerely, Snarcasaur.

**Comment by wandgrab** [comment]
![bildschirmfoto 2016-08-13 um 17 31 47](https://cloud.githubusercontent.com/assets/21010151/17644024/fcc68b64-617b-11e6-9f63-39cf536ebaa2.png) 
After the htmlfile, the app doesnt respondes anymore.

**Comment by itzcreamy** [comment]
i am having the exact same issue.

**Comment by Nader-Sl** [comment]
I am aware of this issue, for now try:

java -jar Hackemon.jar -Xms512 -Xmx2048

**Comment by icecubeice** [comment]
@Nader-Sl still wont work on mine, stuck on gray screen

**Comment by tolinwei** [comment]
Also tried new memory parameter, not working.

**Comment by itzcreamy** [comment]
okay guys im not sure if this will work for all of you , but it worked for me. its really simple lol. so all i did was java -jar Hackemon.jar -Xms512 -Xmx2048 in terminal , then that opened the jar file , but before the gray screen shows up spam the run.bat file and keep clicking a random key. not sure how that works but it worked for me ! :D have a great day guys!

**Comment by ciannaaperta** [comment]
How can you possibly run a .bat file on a mac........... still stuck what a shit.

**Comment by elvinon** [comment]
guys i heard that you can make it work by replace the current settings with the v1.5 settings, so if one of you have it can you share it here?

**Comment by charlestephen** [comment]
In terminal, _cd_ into the directory of Hackemon-master. Then type: _java -jar Hackemon.jar -Xms300m -Xmx1200m_
