### ISSUE TITLE
bot stopped working?

### ISSUE THREAD

**Issue by BombNuker** [Nader-Sl/Hackemon#40]
Bot doesn't move and when i restart the bot, it doesn't show anything after the ssuccessful login

**Comment by Muuuri** [comment]
Yes same for me. No pokestops are showing and nothing happends.

**Comment by Mangoeis** [comment]
Same problem here. Yesterday the bot worked fine. Tried re-downloading it, but still doesn't work. Tried 2 different accounts.

**Comment by tannerr12** [comment]
Yup tried 2 different accounts it just says going to pokestop than doesn't even move was working yesterday just fine

**Comment by lietome87** [comment]
Might have been flagged with an IP Ban or a softban

**Comment by Evertvaningen** [comment]
Working fine for me ;)
