### ISSUE TITLE
Bot crashes every 20 minutes

### ISSUE THREAD

**Issue by lietome87** [Nader-Sl/Hackemon#42]
no matter which location I use, it always crashes after about 20 minutes of so. I'm doing it like a normal play the game. Anyone know what's causing this crash?

**Comment by Evertvaningen** [comment]
What are your computer specs?

**Comment by lietome87** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x5ffa0e72, pid=265800, tid=266028
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) Client VM (25.31-b07 mixed mode windows-x86 )
# Problematic frame:
# C  [jfxwebkit.dll+0xa10e72]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x196dec00):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=266028, stack(0x1bea0000,0x1bef0000)]

siginfo: ExceptionCode=0xc0000005, writing address 0xbbadbeef

Registers:
EAX=0x00000000, EBX=0x00017000, ECX=0x77565358, EDX=0x1beee620
ESP=0x1beee610, EBP=0x00008000, ESI=0x00000000, EDI=0x00010000
EIP=0x5ffa0e72, EFLAGS=0x00010282

Top of Stack: (sp=0x1beee610)
0x1beee610:   1beee620 fffffffe 1beee64c 7753623f
0x1beee620:   77536244 7c18ade3 00010000 00007fff
0x1beee630:   00017000 1beee624 1beee650 1beee860
0x1beee640:   775771d5 10a48517 fffffffe 1beee65c
0x1beee650:   75bd6d2a 00000008 00007fff 1beee66c
0x1beee660:   75bae59e c0000017 00017000 1beee688
0x1beee670:   75bae600 ffffffff 00000000 00000000
0x1beee680:   00002000 00000004 00008000 5ffe2309 

Instructions: (pc=0x5ffa0e72)
0x5ffa0e52:   8d 4c 24 04 51 6a 21 6a 00 ff d0 0f b7 c0 eb 02
0x5ffa0e62:   33 c0 83 c0 fe 50 8d 54 24 0c 52 e8 1e ff ff ff
0x5ffa0e72:   c7 05 ef be ad bb 00 00 00 00 33 c0 81 c4 8c 00
0x5ffa0e82:   00 00 ff e0 cc cc cc cc cc cc cc cc cc cc 83 ec 


Register to memory mapping:

EAX=0x00000000 is an unknown value
EBX=0x00017000 is an unknown value
ECX=0x77565358 is an unknown value
EDX=0x1beee620 is pointing into the stack for thread: 0x196dec00
ESP=0x1beee610 is pointing into the stack for thread: 0x196dec00
EBP=0x00008000 is an unknown value
ESI=0x00000000 is an unknown value
EDI=0x00010000 is an unknown value


Stack: [0x1bea0000,0x1bef0000],  sp=0x1beee610,  free space=313k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jfxwebkit.dll+0xa10e72]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2885  com.sun.webkit.Timer.twkFireTimerEvent()V (0 bytes) @ 0x029ef459 [0x029ef420+0x39]
J 20634 C1 com.sun.webkit.Timer.fireTimerEvent(J)V (65 bytes) @ 0x0267129c [0x02671050+0x24c]
J 20513 C1 com.sun.webkit.Timer.notifyTick()V (29 bytes) @ 0x028040b4 [0x02803f90+0x124]
J 20053 C1 javafx.scene.web.WebEngine$PulseTimer$$Lambda$89.pulse()V (4 bytes) @ 0x02a6dd3c [0x02a6dd10+0x2c]
J 20950 C1 com.sun.javafx.tk.Toolkit$$Lambda$163.run()Ljava/lang/Object; (8 bytes) @ 0x02a071b8 [0x02a07190+0x28]
v  ~StubRoutines::call_stub
J 1477  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object; (0 bytes) @ 0x0286a0c7 [0x0286a060+0x67]
J 19374 C1 com.sun.javafx.tk.Toolkit.firePulse()V (279 bytes) @ 0x0272f540 [0x0272ef70+0x5d0]
J 19574 C1 com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Z)V (144 bytes) @ 0x02777fac [0x02777f10+0x9c]
J 19463 C1 com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$59.run()V (8 bytes) @ 0x028be93c [0x028be910+0x2c]
J 19618 C1 com.sun.glass.ui.InvokeLaterDispatcher$Future.run()V (91 bytes) @ 0x02788df0 [0x02788dc0+0x30]
v  ~StubRoutines::call_stub
j  com.sun.glass.ui.win.WinApplication._runLoop(Ljava/lang/Runnable;)V+0
j  com.sun.glass.ui.win.WinApplication.lambda$null$141(Ljava/lang/Runnable;)V+7
j  com.sun.glass.ui.win.WinApplication$$Lambda$55.run()V+8
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
