### ISSUE TITLE
graphical glitch

### ISSUE THREAD

**Issue by swiftwolf133** [Nader-Sl/Hackemon#43]
the "game" part of the window is overlapping the rest of the window. every time the bot dose an action it dose it again. almost imposible to change any settings or read the log :/ need fix.
I am running windows 7, thats all i can think of as a problem

**Comment by maxlehot1234** [comment]
Any screenshot? I twould be much better than a text.

Thanks

**Comment by swiftwolf133** [comment]
[http://i.imgur.com/RCDVjJT.png](url) 
hope that works :)
all the buttons and where they are suppose to be but the graphics are pushed to the top left :/

**Comment by Evertvaningen** [comment]
Picture won't load 040 error

**Comment by Evertvaningen** [comment]
Nope, 404 Error
![image](https://cloud.githubusercontent.com/assets/21038293/17676924/de6adfec-6330-11e6-8009-25ddf96649c7.png)

**Comment by swiftwolf133** [comment]
copy paste the link. 
it thinks its supose to open in github.com
