### ISSUE TITLE
Why no source code?

### ISSUE THREAD

**Issue by KamuelaFranco** [Nader-Sl/Hackemon#48]
Is there a reason we can't validate the source on this? Do you not want to use an open source license? Was this an oversight, or do you plan to keep it proprietary?

**Comment by maxlehot1234** [comment]
When his website was ready, he willput it on his website. It is a private project in fact, but download access for public.

**Comment by fuckNIANTIC** [comment]
dont put it up, im sure many of us prefer it to be kept private. as soon as its up fucking Niantic will try its best to DDoS it.
