### ISSUE TITLE
Lost configuration after close

### ISSUE THREAD

**Issue by maxlehot1234** [Nader-Sl/Hackemon#49]
Hi, to change the longitude/latitute, I need to close hackemon and reopen so it can take effect BUT,
I lost all exluded pokemon config and all items recycle configuration and humanity config...

Is it possible to fix this? It simply doesn,t read the settings.yml on start, because the settings.yml contain the item recycle, but not added into hackemon

If you can fix this, it could be really nice @Nader-Sl

**Comment by PokemonAddict** [comment]
same here

**Comment by VXT108** [comment]
same
