### ISSUE TITLE
stucked in accepting any level rewards

### ISSUE THREAD

**Issue by SF1997** [Nader-Sl/Hackemon#52]
When I reached to lvl 6 I paused the bot then I opned my account (PTC) on phone to check if that work fine and it does but when I back to Bot it says 'Accepting any level rewards' then it wouldnt do anything just stucked. (sorry for my english ;-; )

**Comment by maxlehot1234** [comment]
Are you sure that your login are good? Did you try to close and reopen the hackemon tool?
Did you try to unban you using quickspin 1.3, just to be sure that you are not ban?
Are you sure that you have Java 8 installed.

You use Mac, Linux or Windows? Fix the issue, if there is an issue could be different base on the system.

**Comment by SF1997** [comment]
It logins fine also I tried to close and reopen but I didn't try quikspin however I checked by phone I don't get ban. Already have that version of Java. I use Windows 10 and I had installed all drivers that needed

**Comment by SF1997** [comment]
http://imgur.com/a/or6Kt

**Comment by maxlehot1234** [comment]
Did you try to stop the bot, close the bot and reopen it?
Do not forget to reconfigure it after you closed it, it lost soe config...

**Comment by SF1997** [comment]
Man I got the solution just delete setting.json and open bot then it wouldnt stuck. btw thanks a lot for help me to figure out xD
