### ISSUE TITLE
Zero xp then softbanned for a while

### ISSUE THREAD

**Issue by dgtalchal** [Nader-Sl/Hackemon#53]
I just tried the bot last night and i like it. One issue though so far, I observed that it runs smoothly until it reaches a random pokestop and gets zero xp then just stops. I try stopping it and logging into my mobile and I find myself soft banned. I cannot see any pokestops. I tried logging into my other account and i can't see anything either. Was i soft banned? But after an hour, i can log in again. This only happens on one account with a full bag.

Also, i cannot donate from my country.

**Comment by PokemonAddict** [comment]
same here

**Comment by PokemonAddict** [comment]
it's an ip ban. try it!
