### ISSUE TITLE
Ideas for New Features

### ISSUE THREAD

**Issue by VXT108** [Nader-Sl/Hackemon#54]
I have scanned the issues and decided to make a list of features that people want. If anyone thinks of any more ideas comment them. If Nader-Sl does not reply I will message him on discord.

1. curveball 

2. Excellent throw percentage option (Currently every of my catch gives me 210XP which meant that I'm having 100% excellent rate. Possible to toggle this off to avoid suspicions?)

3. Delay in between catching pokemon / stops

4. For Pokemon tab have filters such as cp, alphabetical, iv

5. When re-login let Hackémon remember the last GPS location or else it jumps back to the manual GPS location. This is Ban dangerous...

6. Auto center map on player

7. Normal walker preset speed 12Km/h

8. Pokémon Gym icon on map option

9. Bot taking breaks to rest

10. Hatch eggs

11. Recycle item delay time option

12. An option for incense: This could be useful to get pokemons and increase

13. An option to keep Pokemons that have more than (amount specified) CP

14. Maybe an option to define a maximum radius. I know there is the radar meter. But something to prevent the bot to go away from a place.

15. Option for hard to catch pokemons. Try with 1-2 pokeballs and if this not work, try with great and ultra pokeballs.

**Comment by maxlehot1234** [comment]
#38 Check this too

**Comment by Joannou1** [comment]
+ Better config saving
+ Default pokemon not to transfer (Caught a CP 900 Pikachu and it transferred it because the config didn't save, RIP.)

**Comment by PokemonAddict** [comment]
Giving a limit for maximum limit of pokestops or catching pokemons in one session/day/hr

**Comment by Evertvaningen** [comment]
Clickable Pokestops on map to intand remap the walk route ;)

**Comment by whiskey2wine** [comment]
dynamic walking speed

**Comment by weslleyvreal** [comment]
auto evolution pokemons

**Comment by KutPT** [comment]
egg hatcher?

**Comment by fuckNIANTIC** [comment]
dynamic walking speed would be best for the mean time, if you could write it up.

**Comment by chaitat** [comment]
random walk speed from Pokestops to Pokestops and set min/max speed

**Comment by chofo** [comment]
Maybe an option for turn it off with timer, or when get banned stop automaticly

**Comment by Cybereu** [comment]
Farm at Lured Pokestops.

**Comment by Cybereu** [comment]
List of good farm places know by the community and editable

**Comment by thorclaw** [comment]
A timer so it works for 2-3-4 hours and then it completely logs off.

**Comment by CrystalEcho** [comment]
I suggest 3 hours botting time then automatically pause for 1 hour rest then reconnect again after 1 hour. 

A session timer on screen would be great  aswell.

**Comment by CrystalEcho** [comment]
Another thing, powering up your pokemon from the bot would be a great option also so you can see the IV, and hopefully the pokemons skills wil show also.

**Comment by CrystalEcho** [comment]
Standing on one spot and only catching pokemons that will spawn within the area. Like in the midle of 4 pokestops.

**Comment by VXT108** [comment]
![capture2](https://cloud.githubusercontent.com/assets/20883086/17736622/79ba6a30-644e-11e6-89ec-23ebe78532f4.PNG)

**Comment by Joannou1** [comment]
^ Sweet, thanks for getting stuff to him.

Also, I think a Pokestop blacklisting method would be good (click it, option box pops up, toggle blocking, perhaps shade the icon for it to be grayed out)
This is because the bot tends to wander off too far from a central area through a path of Pokestops that are spaced out far apart. It then gets stuck there and doesn't find its way back.

**Comment by CrystalEcho** [comment]
One more thing. Since the new version 1.51 is not working very well for most of the users maybe we can have the option to use the old version or to have a prompt to allow update or not..

**Comment by Cybereu** [comment]
Show how much candies for each pokemon and intregated [Pidgeycalc](http://www.pidgeycalc.com/)

**Comment by daisukeDan** [comment]
can you add a feature use auto-use lucky egg when incubation egg is hatched ?
