### ISSUE TITLE
we need a mobile IP for botting?

### ISSUE THREAD

**Issue by r4fnex** [Nader-Sl/Hackemon#57]
Hello guys :)

Is it possible that we need a mobile IP?
So can find out that we play with a computer IP pokemon go?
or which is excluded the check the IP with locality?

many players the only nox player have used are to banned.....
that is, they have found that we have been with for example German IP on computer in NY or we play at home with no mobile IP.

(sorry for my bad english)

**Comment by Evertvaningen** [comment]
Hm, intresting... Let's check my ip location

**Comment by PokemonAddict** [comment]
yeah that's clear but why you don't use a VPN? standard

**Comment by thorclaw** [comment]
What's the point of using a vpn, if you bot right where you live?
