### ISSUE TITLE
Bot can log in. Phone can't

### ISSUE THREAD

**Issue by swiftwolf133** [Nader-Sl/Hackemon#58]
As title says, bot logs in just fine and gets pokestops/pokemon. On my phone i get a "unable to authenticate, please try again" message. have been this way for 6 hours.

**Comment by dakeeper** [comment]
Banned.

**Comment by thorclaw** [comment]
Not banned. If bot logs in, you are not banned. Try to uninstall the POGO app, wait a couple hours and reinstall it.
Don't log in with your phone while botting. Give it some time, turn the location off, and then login.

**Comment by swiftwolf133** [comment]
I waited for around 24 hours and it now works fine
