### ISSUE TITLE
Pls change pokesnipe site for http://pokesnipe.de/

### ISSUE THREAD

**Issue by ArresGold** [Nader-Sl/Hackemon#6]
This the best pokesnipe sait http://pokesnipe.de/

**Comment by Nader-Sl** [comment]
thanks ill add that as well

**Comment by Nader-Sl** [comment]
Hmm, it says "Note: Pokemon not verified may be not catchable"

**Comment by ArresGold** [comment]
I used all pokemon snipe saits and this sait work the best of them. 90+% coordinates are true, but on another sait every time we see: "No pokemon here". Sorry for my bad English)

**Comment by maxlehot1234** [comment]
@Nader-Sl This mean that all verified pokemon are really there... Not verified pokemon in the list can be missing or simply doesn't exist.


I can confirm that ALL verified pokemon are whre pokesnipe say


Sorry for my english, I am french
