### ISSUE TITLE
Character Doesn't Move and Continuously Says its going to a Pokestop v2

### ISSUE THREAD

**Issue by deadviper123** [Nader-Sl/Hackemon#61]
So if you my last post you would know the problem was I was ip banned. but now I can tell you the problem still persists. After botting for around 4 hours I stopped and then about 2 hours later I tried to start it again. But the says I log in but it does not move and just say going to a pokestop. I can see the pokestop just no route is being made. Also I stopped hakemon and opened up pokemon go on my phone and it works fine I can catch poke and and spin pokestops.

**Comment by SF1997** [comment]
Try to delete ur settings.json don't forget to Back up it then check if that works

**Comment by infslash** [comment]
same problem here, doesnt work.
