### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sQuter** [Nader-Sl/Hackemon#62]
In version 1.5.1 i see a bug no player info and player pokemons :/ say 'Start' to login(Character Started and walking)

**Comment by thorclaw** [comment]
Same here. No stats showing, no nickname, nothing at all. Everything is "0".

However, the bot works.

**Comment by Zexion1985** [comment]
Hello I would like to also confirm the bug with no stats, nickname, ect. The bot is running just fine just no stats at all.
