### ISSUE TITLE
Wont Open

### ISSUE THREAD

**Issue by DatBoiInABox** [Nader-Sl/Hackemon#63]
Running the latest version of Java and Hackemon  (Mac) and when i open the .jar a window opens but its just grey then i get "Hackemon is not responding"

**Comment by CaptSquirrely** [comment]
Am having the same issue. 
Mac OS X El Capitan 
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
With most current version of Hackemon

Jar opens to grey screen then times out. No error code displayed

**Comment by CaptSquirrely** [comment]
[Hackemon Error Message.txt](https://github.com/Nader-Sl/Hackemon/files/421504/Hackemon.Error.Message.txt)

Attached apple error report

**Comment by aboxx** [comment]
I have the same issue with Mac OS

**Comment by pokehell** [comment]
i can open hackemon 1.5 yesterday whole day. but today after i updated to 1.51, my mac wasnt able to load the hackemon. just grey square popup and nothing else. Only thing i can do is force quit. I did reinstall java8 101 and java8 102 still no joy. Please assist

**Comment by barrettdmize** [comment]
I am having the same issue. Please help

**Comment by BigRedCrayon** [comment]
Me too i re-downloaded it and it started to work somewhat but now nothing.

**Comment by reporting4** [comment]
was working fine with last patch but now it wont open

**Comment by igormursa-newstore** [comment]
make sure that your firewall also allows it, in my case the firewall was blocking the app

**Comment by pokehell** [comment]
firewall is fine someting isnt right

**Comment by pokestop400** [comment]
can you please send me the old settings.json file i can't find it anywhere @pokehell

**Comment by pokestop400** [comment]
@pokehell nvm found it thanks for the help

**Comment by malfr** [comment]
@pokestop400 Please post link to the file or text in it :)

**Comment by zackebth** [comment]
@pokestop400 Yes please link it :) would be great (y)

**Comment by elvinon** [comment]
@pokehell @pokestop400 please send us the file or text ! even the v1.6 is not working

**Comment by muhdarifaiman** [comment]
https://www.dropbox.com/s/5xjau3i2nidlhu0/settings.json?dl=0

**Comment by lastorder999** [comment]
I am have the same issue.
