### ISSUE TITLE
Java Jar won't launch

### ISSUE THREAD

**Issue by Johndiddymoma** [Nader-Sl/Hackemon#64]
The Java JAR file "Hackemon.jar" could not be launched.

**Comment by ishort2205** [comment]
does it show a grey screen

**Comment by ishort2205** [comment]
or it doesnt launch at all

**Comment by fuckNIANTIC** [comment]
it shows grey screen, any fix???

**Comment by igormursa-newstore** [comment]
I started it from the terminal as Run.bat, and it got stuck at first step `htmlFile: /html/maps.html`

**Comment by mohojojo** [comment]
Hi! I've download the new 1.51, and copied the old settings.json to the new folder, and it started to work.

**Comment by igormursa-newstore** [comment]
make sure that your firewall also allows it, in my case the firewall was blocking the app

**Comment by Johndiddymoma** [comment]
it doesn't launch at all it just says the java jar can't be launched

**Comment by lyssebabz** [comment]
it says 'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by lyssebabz** [comment]
for me

**Comment by Neimo21** [comment]
For me as well @lyssebabz

**Comment by lyssebabz** [comment]
it's weird
