### ISSUE TITLE
player wont move

### ISSUE THREAD

**Issue by ishort2205** [Nader-Sl/Hackemon#65]
player stops moving and says walking to pokestop continuously
![screen shot 2016-08-16 at 8 47 15 pm](https://cloud.githubusercontent.com/assets/21071353/17721819/b37e7416-63f2-11e6-891a-06601bae894c.png)

**Comment by ishort2205** [comment]
after closing only shows a grey screen

**Comment by kg56** [comment]
I have the exact same issue i've tried uninstalling java and re-installing it but unfortunately it  still doesn't help

**Comment by tannerr12** [comment]
Had this issue it went away after a few hours
