### ISSUE TITLE
V1.51 not showing character detail

### ISSUE THREAD

**Issue by twk4924** [Nader-Sl/Hackemon#66]
after auto updated to v1.51

bot are working fine but dint showing my character detail  ( level , xp gained bla bla bla)
and pokemon function are not working too after updated v1.51 (v1.5 are working)

are anyone face same problem with me?

**Comment by bugman840** [comment]
yea having same issue

**Comment by PenjagaHati** [comment]
Sorry want to ask, where the download

**Comment by palmerd1603** [comment]
It's not working for me either, but in defense, It hasn't worked for the last two updates.

**Comment by thorclaw** [comment]
For me it was fully working untill this last update, yesterday. Now it doesn't.

**Comment by twk4924** [comment]
hope they are fixing this problem
it dangerous to bot without those detail

**Comment by Zexion1985** [comment]
Hello I would like to also confirm the bug with no stats, nickname, ect. The bot is running just fine just no stats at all.

**Comment by kipperjx2** [comment]
confirmed fix. sign in on phone, choose team, spin poke stop catch first pokemon choose nickname and fixed. your welcome.

**Comment by marks89** [comment]
@kipperjx2 same problem and not resolve with your fix :(
