### ISSUE TITLE
A Few Issues

### ISSUE THREAD

**Issue by Noah989** [Nader-Sl/Hackemon#67]
The Jar won't run there is just a black screen
Pokemon won't connect (doesn't show what pokemon are caught in the pokemon tab)
So I cant Evolve or Manually transfer

**Comment by Noah989** [comment]
I am on Mac

**Comment by BigRedCrayon** [comment]
As am i.
Grey screen, timed out, not responding.

**Comment by nadavgabay** [comment]
Same problem on Mac

**Comment by briannarit** [comment]
is there any fix to this?
