### ISSUE TITLE
GoogleMapView.mapResized: triggering resize event

### ISSUE THREAD

**Issue by maxlehot1234** [Nader-Sl/Hackemon#69]
Hi get this error each time I zoom-in, zoom-out:
GoogleMapView.mapResized: triggering resize event

I am under Windows 10 with java 8

**Comment by Joannou1** [comment]
I don't think this is an error, just a debug message.
Shouldn't cause issues.

**Comment by maxlehot1234** [comment]
I know, but just weird :P :P
Anyway the dev doesn,t answer us, so we create tickets for nothing...
