### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by thorclaw** [Nader-Sl/Hackemon#70]
It would be great if we could put a timer on the whole bot so it never runs for too long. We would be able to define if we want the bot to run for 2 ou 3 hours, and then it stops and logs off completely. 

Would be even better if it had a recycling method for working time and stopping time. 
Ex. Bot runs for 2 hours  - stops for 1 hour - runs for 2 hours - stops

**Comment by dakeeper** [comment]
Yep this should be good if the coder can implement it.
But this is also suspicious. The Playtime and the Pause time should be randomized
As Sample:  Play 2 hours +/- Random minuten from 0-30, Then Pause 3 hours + /- Random minutes from X-Y

**Comment by twk4924** [comment]
i think it is no necessary,
if you dont wan to get solf ban or perm ban,

*do not over 1000 pokestop a day
*do not over 1000 pokemon a day
*set human walk with road walk and the speed 3km/h
(v1.51 player status are not workings , so please be careful if you duwan to get ban)

u can use road fly on shopping mall

from lv1~26lv , i still not getting any solf ban (touch wood)

suggestion for me:
# add exclude tranfer if IV are xx%
# add chose pokestop we want to go (for me sometime the pokestop are quite near from current pokestop but the bot choose others , im in road fly mode)

**Comment by thorclaw** [comment]
It's just that we would never forget it running over and over.

**Comment by twk4924** [comment]
if possible 
please add any hotkey to hide the icon from taskbar :)

**Comment by batoto05** [comment]
i like tha feature where pokestop we want tog go hopefully it will be added soon :D
