### ISSUE TITLE
Session Summary

### ISSUE THREAD

**Issue by CrystalEcho** [Nader-Sl/Hackemon#71]
Hi guys, I just updated my hackemon from 1.5 to 1.51 and now the Session Summary is not showing, it doesn't show anything but the bot functions ar all working except for  that, anyone know how to fix this? Not showing level, it still shows start to login and lvl 0, pokemons caught and pokestops captured both 0.

**Comment by CrystalEcho** [comment]
Oh by the way, my cousin have just freshly installed hackemon and the stats are working perfectly fine for him. I tried deleting the existing file and redoing everything again but still no luck.

**Comment by CrystalEcho** [comment]
Even the owned pokemons are not showing.

**Comment by cirios** [comment]
I have the same problem after the update of today..

**Comment by CrystalEcho** [comment]
But the thing is my cousins freshly installed bot is working perfectly fine for him.. Hmmmmm..

**Comment by CrystalEcho** [comment]
Fixed, Thanks Nader..
