### ISSUE TITLE
Recycle and Catch problem

### ISSUE THREAD

**Issue by JackSbirrow** [Nader-Sl/Hackemon#72]
I don't know why, but the bot gets the pokestops experience (and the stuff) but all the pokemon flee.
I have this problem even on my phone. If I would be soft-banned I couldn't get the pokestops, but I can.
So what's the problem?
Then, why does the bot recycle my Great-Ball and Ultra-ball If I did not set it on the bot? I want to recycle just Potion and Revive, but the bot recycles even the balls. Why? How do I fix it?

**Comment by CrystalEcho** [comment]
Mine is recycling just fine. Have you checked if great balls and ultra balls are on the list?

**Comment by vinisdl** [comment]
![image](https://cloud.githubusercontent.com/assets/6885761/17732745/b144f1fa-6449-11e6-8c07-2905ca9aa3cf.png)


this bug

**Comment by JackSbirrow** [comment]
They are not in the list. There are just Potions and Revives.
@vinisdl Restart the app
