### ISSUE TITLE
Sniping not possible

### ISSUE THREAD

**Issue by Ansgasm** [Nader-Sl/Hackemon#73]
Is it me, or is the bot not able to snipe anymore?
Whenever I try to snipe a pokemon it does not find it.

**Comment by wEisB0145** [comment]
Its because the Pokemon isnt there. It is not the fault of the bot

**Comment by batoto05** [comment]
yup me also when want to snipe the target no available

**Comment by thorclaw** [comment]
Works fine for me

**Comment by darellv** [comment]
can you teach me how @thorclaw im using 1.51. TIA

**Comment by thorclaw** [comment]
Go to http://www.pokesnipers.com chose your pokemon, select and copy its coordinates.
Go back to Hackemon, paste the coords you copyed from pokesnipers, to that editbox next to the Snipe button, chose the pokemon you want to catch by clicking that dropdown box and selecting it.
Then click Snipe.

I advise you to not do this very often though. Maybe just once a day, or you'll get banned forever.

**Comment by darellv** [comment]
banned already :(
