### ISSUE TITLE
Near pokepoints

### ISSUE THREAD

**Issue by isoueu** [Nader-Sl/Hackemon#76]
Hello guys, nice work here,

is too hard to make bot get the pokestops in this range ? all the time he passing over a pokestop and don't get it !

In mineapolis, 45.03005555153756, -93.31929534673691 we have 6 pokestops can be catch staying at same place, but the bot still walking like 1 km to get all the 6.

**Comment by wEisB0145** [comment]
Settings -> Humanizer -> Google Map Root Findinf Heuristic -> Road_Fly

**Comment by isoueu** [comment]
I'm talking about range, did you know what this mean ? I'm not talking about route...
