### ISSUE TITLE
Stops at 1 Pokestop

### ISSUE THREAD

**Issue by tacosausje** [Nader-Sl/Hackemon#77]
Hello,

I was running my bot for quite a while and it suddenly stopped. My character stayed at 1 pokestop and I couldn't use the snipe option anymore. I tried re-run the bot and re-download but the bot still does the same thing. Please help me :3 :+1:

**Comment by wEisB0145** [comment]
Maybe your IP is banned and the bot cannot loot it. If so then buy a proxy.
What you could try is leave the bot 1-2 minutes and see what happens

**Comment by Nickepicke** [comment]
Seens like many people have that same peoblem if u scroll around forums. Its this pathetic version. I hope they get it right!

**Comment by MikJohnson** [comment]
Same. I didn't have problems at all, until yesterday and today...

**Comment by ciannaaperta** [comment]
Not a ban AT ALL. It just keeps spinning the same pokestop. Of course it's not getting exp. How much exp would you get if you keep spinning the same pokestop playing normally? We just need a way to tell the bot to head the next pokestop.

**Comment by MikJohnson** [comment]
Try 

> ROAD_FLY

 instead of:

> ROAD_WALK

This fixed my problem.

**Comment by ciannaaperta** [comment]
Already enabled. Found a better solution: switched to ninja bot.
