### ISSUE TITLE
Envolving (Pokemon GUI)

### ISSUE THREAD

**Issue by wEisB0145** [Nader-Sl/Hackemon#78]
When you click Envolve without an Pokemon selected in version 1.51, it always says "wait...."
After pressing it w/o a Pokemon selected:
* The button does not work anymore
* The Transfer button still works

**Comment by engemerson** [comment]
buton evolue dont work, and no evolue automatic,, need calculate Pokestop more prox. my local.

**Comment by wEisB0145** [comment]
what?
