### ISSUE TITLE
Can't Move anywhere, continues to same pokestop

### ISSUE THREAD

**Issue by ShiroShini** [Nader-Sl/Hackemon#80]
Ok so it was working fine until this morning. Now it keeps trying to move to a pokestop and the character isn't in the right place and won't move at all. heres the error in the console

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.hackemon.new.K0M0qVvnMS(Unknown Source)
        at com.hackemon.Hackemon.main(Unknown Source)

**Comment by JackSbirrow** [comment]
Same here, and if I try with my phone the pokestops says "Error,try later"

**Comment by aboxx** [comment]
soft ban. wait a few hours before logging in.

**Comment by ShiroShini** [comment]
is it? I can log into my phone fine but I dont have any pokestops around me or pokemon so I cant test the soft ban

**Comment by aboxx** [comment]
Hmm ok that's different. Not sure. I had logged in with my phone and just got the "error, try later" at pokestops it but resolved a couple hours later.

**Comment by ShiroShini** [comment]
just to clarify, I don't have pokemon or pokestops because there are none around me, not because they're not showing up XD I live in a really rural area

**Comment by frodo024** [comment]
I believe thats an "ip ban" I have heard of it before where people can log in but dont see pokemon or pokestops

**Comment by frodo024** [comment]
Oh sorry didnt finish reading your comment about rural area, so nevermind.

**Comment by ShiroShini** [comment]
yea XD I think its eitehr program side or something with my java. Don't know which one.

**Comment by aboxx** [comment]
You could use Poke Go ++ and walk to an area with pokestops.

**Comment by ShiroShini** [comment]
nah I won't risk that much. Im going into town in a little while, Ill just check when I'm there. Ill let you know when I get back@

**Comment by engemerson** [comment]
soft ban. wait fave hours to test again

**Comment by ShiroShini** [comment]
Confirmed not a soft ban because I was just in town and could catch pokemon, spin pokestops and do everything normally. It has to be something either with my settings/java or the program itself. still the same error.

**Comment by arno608rw** [comment]
@aboxx Poke Go ++ download?

**Comment by ShiroShini** [comment]
So I don't know what caused it or what fixed it, but its working now :D I guess if it happens to anyone else, wait it out for about a day or so.

**Comment by ciannaaperta** [comment]
My bot keeps spinning the same pokestop forever and ever. It's not a ban. It just won't move to the next pokestop.
