### ISSUE TITLE
after update no pokestops and cant login on phone

### ISSUE THREAD

**Issue by charmcityace** [Nader-Sl/Hackemon#81]
The last version worked fine, after my app updated yesterday. After update yesterday i logged in, walked to a few pokestops, and suddenly... all stops disappeared. Tried to login on my phone a few minutes later and got "failed to get game data from server" error message. My PTC account is getting the same messsage.

**Comment by tazzcom** [comment]
Perma ban I do believe. =(

**Comment by charmcityace** [comment]
say it aint so!
i thought this thing was ban-free!
how can i run the previous version without the auto-update?

**Comment by aboxx** [comment]
It's definitely perm ban, happened to one of my accounts that I had run all day and all night. The program isn't 100% ban free, but it's a lot better than previous ones. You just have to make sure you run the bot in a humanlike way. So don't run it 24hrs/day, only do like 4-8hrs. Don't visit more than 1000 pokestops or catch more than 1000 pokemon per day. Have it at a low speed, set a low catch fail rate, and delay pokemon and catch encounters. Also don't do too many activities at once, like a bunch of transferring and evolving.

**Comment by congtran1188** [comment]
did you log in to your phone with your location disabled?

**Comment by engemerson** [comment]
IP ban wait 12 hours to test agian Closed

**Comment by charmcityace** [comment]
my username was recycled its been a full 24 hours
