### ISSUE TITLE
 Stopped working .

### ISSUE THREAD

**Issue by engemerson** [Nader-Sl/Hackemon#83]
Stopped working .
![sem titulo](https://cloud.githubusercontent.com/assets/20991918/17751737/d4d30ac6-649e-11e6-85db-9a2656c143fd.png)

**Comment by Muuuri** [comment]
Might be a soft ban, happend to me many times. If it doesnt work after around 1 hour, then i dont know.

**Comment by engemerson** [comment]
I will wait 12 hours paragraph Check the problem and solved.
