### ISSUE TITLE
Can't open (gray screen)

### ISSUE THREAD

**Issue by malfr** [Nader-Sl/Hackemon#87]
No fix yet, someone posted that replaced "settings.json" file with the last version one (1.5) and worked, can anyone confirm? If that's the case, please post a link or the text in it. Thanks. 

(edit) I'm on mac btw, OSX El Capitan with the latest java version.

**Comment by aboxx** [comment]
It worked for me.

https://www.dropbox.com/s/emhootmnp5uxwq5/settings.json?dl=0

**Comment by Driesboy** [comment]
duplicate #13
