### ISSUE TITLE
NO TRAINER INFO FIX!! :)

### ISSUE THREAD

**Issue by kipperjx2** [Nader-Sl/Hackemon#90]
Confirmed fix. Sign in on phone, choose team, spin poke stop, catch first pokemon choose nickname and fixed. Your welcome.

**Comment by Driesboy** [comment]
i dont have this

**Comment by CrystalEcho** [comment]
Still not working. This is for new accounts. I'm using my old account and the bot still doesn't show trainer info.. Even if I log in or out from my phone.

**Comment by Driesboy** [comment]
UPDATE YOUR ACCOUNT THAN!

**Comment by CrystalEcho** [comment]
@Driesboy Can you please tell us how does an account get updated? LOL

**Comment by CrystalEcho** [comment]
@Driesboy By Old account I meaning it was the same account I was using on the older versions of the bot and suddenly stopped working on this new version..
