### ISSUE TITLE
but pokestops (Disneyland)

### ISSUE THREAD

**Issue by microonline** [Nader-Sl/Hackemon#91]
I saw a picture on the internet viral someone playing pokemon from Disneyland and there were many pokestops.

Here I leave the location

Latitude: 33.812359

Longitude: -117.918963

https://gyazo.com/7027be76ef60a73604969b93e5cc14ca

**Comment by Driesboy** [comment]
start the bot!

**Comment by fcfidel** [comment]
nothing good there tho
