### ISSUE TITLE
IP SOFTBAN SOLUTION!

### ISSUE THREAD

**Issue by Muuuri** [Nader-Sl/Hackemon#92]
Hello fellow cheaters! I found out a way to bypass IP softban. This does not work for account softban, but if you can't find any pokemons or pokestops on any of your account on your internet, this means you are IP softbanned, Happened to me alot lately, but i want to share a sweet solution with you guys! ;)

This is what you do:
1: go to - https://hide.me/en/    this is a VPN website where you can get a free VPN for 3 days (make a new account after 3 days :D )
2: make an account, download and click connect!! Just like that, you have a new IP and are ready to play pokemon again!

Hope this helped all of you that find yourself trapped with IP softbans all the time like i did a couple of hours ago. Have fun and happy cheating <3

**Comment by thorclaw** [comment]
What if the new vpn ip address is from a place too far away from the place you are botting? Don't you get banned again?
