### ISSUE TITLE
NO player stats and pokemon dont show

### ISSUE THREAD

**Issue by devinroman** [Nader-Sl/Hackemon#97]
i really need to see player stats , makes it risky

**Comment by Driesboy** [comment]
you need to start the bot

**Comment by Mikegomezz** [comment]
i have the same problem, and the bot its running... just dotn show me the pokemons and player stats...

**Comment by kainbr3** [comment]
i have the same problem. I cant see my status or pokemons

**Comment by marks89** [comment]
same problem, yesterday I talked about it with nader, is trying to understand the problem...

**Comment by CrystalEcho** [comment]
Same here. I tried to reinstalling but still not working. If it's working with the others there is is definitely a fix for this.. Grrr.

**Comment by twk4924** [comment]
for me...
player stat & pokemon are working but bot not working : windows 10 ~ 8

player stat & pokemon are not working but bot are working : windows 7

**Comment by marks89** [comment]
form me:
bot working but player stat & pokemon not working 10 64bit

**Comment by Mikegomezz** [comment]
for me too: 
bot working but player stat and pokemon not working Windows10-64bit

**Comment by MikJohnson** [comment]
If you're bot starts and says that you're successfully logged in, but nothings shows up (Pokestops/Player stats). First try to log in on you're phone. If you get the error 

> "Failed to get game data from the server"

, you're probably perma-banned. If this isn't the case for you, you may have an hard/soft ban. Just wait about 3-4 hours, and try again.

**Comment by gokugoku363** [comment]
but its catching pokemon and gettong pokestops but it just doesnt show stats and pokemons

**Comment by Nader-Sl** [comment]
Fixed issue, will be included with other fixes/updates today :)
