### ISSUE TITLE
Can't login with Google Account

### ISSUE THREAD

**Issue by michaelsmith13** [Nader-Sl/Hackemon#98]
Every time I try to login with my Google Account, I get "Wrong Google User/Pass, please redfine account."

I'm wondering if it has to due with the fact that I have Google 2-Step Verification on my account.

**Comment by Driesboy** [comment]
it work fine for me

**Comment by nadavgabay** [comment]
Yes, Google 2-Step Verification blocks the App

**Comment by Nader-Sl** [comment]
disable 2-step auth and make sure you can fully login with gmail (not asking phone verification blocking)
