### ISSUE TITLE
The linear distance is not necessarily the fastest

### ISSUE THREAD

**Issue by MatteCarra** [Nader-Sl/Hackemon#99]
With the new update the bot can walk on the streets, but the nearest pokestop is calculated in linear distance.
![issue](https://cloud.githubusercontent.com/assets/11074527/17764676/34150548-6521-11e6-9ebf-e6232d2c19e3.jpg)

**Comment by yoyos** [comment]
At least it should take the pokestops on its way to prevent the player to come back

**Comment by Roadieee** [comment]
Check this one out at the St. Louis zoo...

![walk](https://cloud.githubusercontent.com/assets/21083920/17816901/2b7c5568-6601-11e6-918a-a567caff9e07.jpg)

**Comment by yoyos** [comment]
That's a good thing to avoid being banned because of too many pokestops :D

**Comment by Roadieee** [comment]
It's awesome at pokemon hunting because it finds lots on those long walks. lol
